---
- name: "apt | ensure Sensu linux signing key present"
  get_url:
    url: https://packagecloud.io/sensu/stable/gpgkey
    dest: /tmp/sensu_gpgkey
    mode: '0600'
    force: true

- name: "apt | load Sensu linux signing key to keyring"
  shell: gpg --dearmor < /tmp/sensu_gpgkey > /usr/share/keyrings/sensu_stable-archive-keyring.gpg

- name: "apt | ensure Sensu repo present"
  copy:
    content: "deb [signed-by=/usr/share/keyrings/sensu_stable-archive-keyring.gpg] https://packagecloud.io/sensu/stable/{{ ansible_facts['distribution'] | lower }}/ {{ ansible_facts['distribution_release'] | lower }} main"
    dest: "/etc/apt/sources.list.d/sensu_stable.list"
  register: sensu_repo

- name: "apt | update cache"
  apt:
    update_cache: true
  when: sensu_repo.changed

- name: "apt | remove temp downloaded Sensu signing key"
  file:
    path: /tmp/sensu_gpgkey
    state: absent
