---
- name: install trusty-media PPA when using Ubuntu 14.04 Trusty
  apt_repository:
    repo: 'ppa:mc3man/trusty-media'
    update_cache: yes
  when: (ansible_distribution == 'Ubuntu') and (ansible_distribution_release == 'trusty')

- name: install latest version of ffmpeg
  package:
    name: ffmpeg
    state: latest

- name: install latest version of mediainfo
  package:
    name: mediainfo
    state: latest

- name: install latest version of mkvtoolnix
  package:
    name: mkvtoolnix
    state: latest
