---
- name: register graphics card info
  shell: lspci | grep -i VGA
  register: graphics_info

- name: Configure Intel graphics drivers and codecs
  include_tasks: intel-graphics-drivers.yml
  when: "'Intel' in graphics_info.stdout"

- name: Configure Nvidia Legacy graphics drivers and codecs
  include_tasks: nvidia-legacy-graphics-drivers.yml
  when: "'NVIDIA' in graphics_info.stdout"

- name: Configure AMD graphics drivers and codecs
  include_tasks: amd-graphics-drivers.yml
  when: "'AMD' in graphics_info.stdout"
