---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"
      skip: True
  when: (gstreamer1_package_name is not defined) or (gstreamer1_plugins_base_package_name is not defined) or (gstreamer1_plugins_good_package_name is not defined)

- name: install latest versions of gstreamer plugins
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ gstreamer1_package_name }}"
    - "{{ gstreamer1_plugins_base_package_name }}"
    - "{{ gstreamer1_plugins_good_package_name }}"

- name: install latest version of Spotify client apt
  include: spotify-apt.yml
  when: ansible_pkg_mgr == 'apt'

- name: install latest version of Spotify client dnf
  include: spotify-dnf.yml
  when: ansible_pkg_mgr == 'dnf'

- name: install latest version of Spotify client yum
  include: spotify-yum.yml
  when: ansible_pkg_mgr == 'yum'

- name: install latest version of Plex media player
  package:
    name: plex-media-player
    state: latest
  when: ansible_os_family == "RedHat"
