---
- name: install latest versions of gstreamer plugins
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - gstreamer1
    - gstreamer1-plugins-base
    - gstreamer1-plugins-bad-free
    - gstreamer1-plugins-good

- name: install latest version of Spotify client apt
  include: spotify-apt.yml
  when: ansible_pkg_mgr == 'apt'

- name: install latest version of Spotify client dnf
  include: spotify-dnf.yml
  when: ansible_pkg_mgr == 'dnf'

- name: install latest version of Spotify client yum
  include: spotify-yum.yml
  when: ansible_pkg_mgr == 'yum'

