---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"
      skip: True
  when: (gstreamer1_package_name is not defined) or (gstreamer1_plugins_base_package_name is not defined) or (gstreamer1_plugins_good_package_name is not defined) or (gstreamer1_plugins_good_extras_package_name is not defined) or (gstreamer1_plugins_bad_package_name is not defined) or (gstreamer1_plugins_bad_free_package_name is not defined) or (gstreamer1_plugins_ugly_package_name is not defined) or (gstreamer1_plugins_ugly_free_package_name is not defined)

- name: install latest versions of gstreamer plugins
  package:
    name:
      - "{{ gstreamer1_package_name | default(omit)}}"
      - "{{ gstreamer1_plugins_base_package_name | default(omit) }}"
      - "{{ gstreamer1_plugins_good_package_name | default(omit) }}"
      - "{{ gstreamer1_plugins_good_extras_package_name | default(omit) }}"
      - "{{ gstreamer1_plugins_bad_package_name | default(omit) }}"
      - "{{ gstreamer1_plugins_bad_free_package_name | default(omit) }}"
      - "{{ gstreamer1_plugins_ugly_package_name | default(omit) }}"
      - "{{ gstreamer1_plugins_ugly_free_package_name | default(omit) }}"
    state: latest

- name: install latest version of VLC
  package:
    name: vlc
    state: latest

- name: install latest version of Spotify client apt
  include: spotify-apt.yml
  when: ansible_pkg_mgr == 'apt'

- name: install latest version of Spotify client flatpak
  include: spotify-flatpak.yml
  when: ansible_pkg_mgr != 'apt'

- name: install openh264 from Fedora Cisco repo
  dnf:
    enablerepo: fedora-cisco-openh264
    name:
      - gstreamer1-plugin-openh264
      - gstreamer1-libav
      - mozilla-openh264
    state: latest
  when: ansible_distribution == 'Fedora'
