---
- name: "dnf | ensure Negativo17.org multimedia repo present for Fedora"
  command: dnf config-manager --add-repo=https://negativo17.org/repos/fedora-multimedia.repo
  when: ansible_distribution == 'Fedora'

- name: "dnf | install latest version of Plex Media Player"
  dnf:
    name: plex-media-player
    state: latest
