---
- name: "flatpak | force repair"
  shell: "/usr/bin/flatpak repair"

- name: "flatpak | install latest version of Spotify installer"
  flatpak:
    name: com.spotify.Client
    state: present
    remote: flathub
  register: install_spotify
  until: install_spotify is not failed
  retries: 5
