---
- name: Add Apt Keys (2017-01)
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=BBEBDCB318AD50EC6865090613B00F1FD2C19886 state=present

- name: Add repository
  apt_repository: repo='deb http://repository.spotify.com stable non-free'

- name: "apt | update cache"
  apt: update_cache=yes

- name: install latest version of Spotify
  apt:
    name: spotify-client
    state: latest
