---
- name: "yum | ensure Negativo17.org repo present"
  yum_repository:
    name: negativo17
    baseurl: http://negativo17.org/repos/fedora-spotify.repo

- name: "dnf | install latest version of Spotify"
  dnf:
    name: spotify-client
    state: latest
