---
- name: Add Apt Keys
  apt_key:
    url: https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg
    state: present

- name: Add repository
  apt_repository:
    repo: 'deb http://repository.spotify.com stable non-free'

- name: install latest version of Spotify
  apt:
    name: spotify-client
    state: latest
    update_cache: true
