---
- name: Add Apt Keys (2019-08-15)
  apt_key: url=https://download.spotify.com/debian/pubkey_0D811D58.gpg id=0D811D58 state=present

- name: Add repository
  apt_repository: repo='deb http://repository.spotify.com stable non-free'

- name: "apt | update cache"
  apt: update_cache=yes

- name: install latest version of Spotify
  apt:
    name: spotify-client
    state: latest
