---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"
      skip: true
  when: (libebur128_package_name is not defined)

- name: install Strawberry dependencies
  package:
    name:
      - "{{ libebur128_package_name }}"
    state: latest

- name: install latest Strawberry from GitHub releases
  import_role:
    name: github-releases
  vars:
    org: strawberrymusicplayer
    repo: strawberry
    filename: strawberry
    arch: "{{ strawberry_arch }}"
    distro: "{{ ansible_distribution_release }}"
    version: latest
    project_url: https://api.github.com/repos/{{ org }}/{{ repo }}/releases
  tags: gh-releases
