---
- name: include Fedora ansible_distribution_release
  include_vars: "../vars/RedHat.yml"
  when: ansible_distribution == 'Fedora'

- name: install latest Strawberry from GitHub releases
  import_role:
    name: github-releases
  vars:
    org: strawberrymusicplayer
    repo: strawberry
    filename: strawberry
    arch: "{{ strawberry_arch }}"
    distro: "{{ ansible_distribution_release }}"
    version: latest
    project_url: https://api.github.com/repos/{{ org }}/{{ repo }}/releases
  tags: gh-releases
