---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"
      skip: True
  when: (apache_package_name is not defined) or (php_package_name is not defined)

- name: install the latest version of Apache
  package:
    name: "{{apache_package_name}}"
    state: latest

- name: install the latest version of PHP
  package:
    name: "{{php_package_name}}"
    state: latest
