---
- name: install latest versions of disk wiping and filesystem recovery tools
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - nwipe
    - testdisk
    - smartmontools
    - nvme-cli
