---
- name: Restart firewall
  service: name=firewall state=restarted

# handlers for fail2ban
- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
  when: service_default_state | default('started') == 'started'

# temporary for debugging failing Travis build #513
- name: fail2ban status
  shell: systemctl status fail2ban.service -l --no-pager
