---
- name: Restart firewall
  service: name=firewall state=restarted

# handlers for fail2ban
- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
  when: service_default_state | default('started') == 'started'
