---
# handlers for firewall
- name: reload firewalld
  shell: firewall-cmd --reload

- name: check firewalld config
  shell: firewall-cmd --check-config

# handlers for fail2ban
- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
  when: service_default_state | default('started') == 'started'
