FROM debian:testing

# update apt and ensure pip is latest version
RUN apt-get update -qq && apt-get install python-pip git apt-transport-https -y && pip install --upgrade --force pip

# combat not having CA Certs installed
RUN pip install pyopenssl ndg-httpsclient urllib3 pyasn1 requests

# setup the james user
RUN useradd -m -c "james" james -s /bin/bash

# install pre-reqs
ENV ANSIBLE_VERSION=latest
RUN if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible ansible-lint; else pip install ansible==$ANSIBLE_VERSION; fi

