FROM centos:8

# update dnf and ensure pip is latest version
RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm && \
    dnf install -y python36 python36-pip git sudo && \
    pip3 install --upgrade --force pip

# combat not having CA Certs installed
# specific version of urllib3 required by docker-py
RUN pip install pyopenssl ndg-httpsclient 'urllib3<1.25,>=1.21.1' pyasn1 requests

# setup the james user
RUN useradd -m -c "james" james -s /bin/bash

# install pre-reqs
ENV ANSIBLE_VERSION=latest
RUN if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible ansible-lint; else pip install ansible==$ANSIBLE_VERSION; fi

