---
- name: create "james" user
  user:
    name: james
    comment: "James"
    shell: /bin/bash
    state: present

- name: Set authorized key
  authorized_key:
    user: james
    state: present
    key: https://github.com/toozej.keys
    validate_certs: True

- name: clone dotfiles from github
  git:
    repo: 'https://github.com/toozej/dotfiles.git'
    accept_hostkey: yes
    dest: /home/james/dotfiles
    recursive: yes
  register: clone_or_pull
  when: not ansible_check_mode

- name: set correct permissions on dotfiles
  file:
    path: /home/james/dotfiles
    recurse: yes
    owner: james
    group: james
  when: (clone_or_pull.changed == True) and (not ansible_check_mode)

- name: setup dotfiles
  raw: sudo -u james /home/james/dotfiles/setup.sh
  when: (clone_or_pull.changed == True) and (not ansible_check_mode)
