---
- name: install vagrant
  package:
    name: vagrant
    state: latest

- name: Install latest version of virt-manager
  package:
    name: virt-manager
    state: latest

- name: install bridge-utils networking
  package:
    name: bridge-utils
    state: latest

- name: Install vagrant libvirt provider on modern distros
  include: vagrant_providers_libvirt.yml

- name: Install vagrant plugins on modern distros
  include: vagrant_plugins.yml
