---
- name: install vagrant
  package:
    name: vagrant
    state: latest

- name: Install latest version of virt-manager
  package:
    name: virt-manager
    state: latest

- name: install bridge-utils networking
  package:
    name: bridge-utils
    state: latest

- name: Install vagrant libvirt provider on modern distros
  include: vagrant_providers_libvirt.yml
  when: not (ansible_distribution == 'CentOS' and ansible_distribution_version is version_compare(7,'>='))

- name: Install vagrant plugins on modern distros
  include: vagrant_plugins.yml
  when: not (ansible_distribution == 'CentOS' and ansible_distribution_version is version_compare(7,'>='))
