---
- name: install vagrant libvirt provider
  package:
    name: vagrant-libvirt
    state: latest
  when: (ansible_distribution_version != "16.04")
  # package not available in 16.04, use https://github.com/vagrant-libvirt/vagrant-libvirt/issues/891 as a workaround

- name: create ~/VMs/vagrant/libvirt_template/ directory
  file:
    dest: /home/james/VMs/vagrant/libvirt_template/
    state: directory
    recurse: yes

- name: lay out libvirt Vagrantfile template
  template:
    src: Vagrantfile_libvirt
    dest: /home/james/VMs/vagrant/libvirt_template/Vagranfile
    owner: james
    group: james
    mode: 0644
