---
- name: install vagrant libvirt provider
  package:
    name: vagrant-libvirt
    state: latest

- name: create ~/VMs/vagrant/libvirt_template/ directory
  file:
    dest: /home/james/VMs/vagrant/libvirt_template/
    state: directory
    recurse: true
    owner: james
    group: james
    mode: 0744

- name: lay out libvirt Vagrantfile template
  template:
    src: Vagrantfile_libvirt
    dest: /home/james/VMs/vagrant/libvirt_template/Vagrantfile
    owner: james
    group: james
    mode: 0644
