---
# instructions from https://balintreczey.hu/blog/firefox-on-ubuntu-22-04-from-deb-not-from-snap/
- name: pin to no snap
  copy:
    content: |
      Package: firefox*
      Pin: release o=Ubuntu*
      Pin-Priority: -1
    dest: /etc/apt/preferences.d/firefox-no-snap
    force: true
    mode: 0644
  when: ansible_distribution == 'Ubuntu'

- name: remove Firefox snap
  community.general.snap:
    name: firefox
    state: absent

- name: remove firefox package
  package:
    name: firefox
    state: absent

- name: remove firefox-esr package
  package:
    name: firefox-esr
    state: absent

# instructions from https://support.mozilla.org/en-US/kb/install-firefox-linux#w_install-firefox-deb-package-for-debian-based-distributions
- name: Add Mozilla signing key
  get_url:
    url: https://packages.mozilla.org/apt/repo-signing-key.gpg
    dest: /etc/apt/keyrings/packages.mozilla.org.asc
    mode: '0644'

- name: setup Mozilla apt repo
  copy:
    content: "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main"
    dest: /etc/apt/sources.list.d/mozilla.list
  register: mozilla_repo.changed

- name: setup Mozilla apt repo priority
  copy:
    content: |
      "Package: *
       Pin: origin packages.mozilla.org
       Pin-Priority: 1000"
    dest: /etc/apt/preferences.d/mozilla

- name: update apt cache
  apt:
    update_cache: true
  when: mozilla_repo.changed

- name: install Firefox from Mozilla repo
  package:
    name: firefox
    state: latest
