---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"
      skip: true
  when: (powerline_fonts_package_name is not defined) or (sensors_package_name is not defined) or (simplenote_arch is not defined)

- name: Ensures ~/.config exists
  file:
    path: /home/james/.config/
    state: directory
    recurse: true

- name: Install latest version of powerline fonts
  package:
    name: "{{ powerline_fonts_package_name }}"
    state: latest

- name: Install latest version of xournal PDF editor
  package:
    name: xournal
    state: latest

- name: Install latest version of Filezilla FTP tool
  package:
    name: filezilla
    state: latest

- name: Install latest version of Terminator
  package:
    name: terminator
    state: latest

- name: Ensures ~/.config/terminator exists
  file:
    path: /home/james/.config/terminator
    state: directory
    recurse: true

- name: lay out Terminator config file
  template:
    src: terminator.conf.j2
    dest: /home/james/.config/terminator/config
    owner: james
    group: james
    mode: 0644

- name: Install latest version of Kitty terminal terminal
  package:
    name: kitty
    state: latest

- name: Install latest version of Calibre
  package:
    name: calibre
    state: latest

- name: Install latest version of CA certificates
  package:
    name: ca-certificates
    state: latest

# available in default Fedora repos
- name: Install latest version of GPXSee
  package:
    name: gpxsee
    state: latest
  when: ansible_distribution == 'Fedora'

- name: Install latest version of Solaar
  package:
    name: solaar
    state: latest

- name: Install and configure Sensors
  include_tasks: sensors.yml

- name: Install Simplenote
  include_tasks: simplenote.yml

- name: Install Slack
  include_tasks: slack.yml

- name: Install Zoom
  include_tasks: zoom.yml

- name: Install Speedcrunch
  include_tasks: speedcrunch.yml

- name: Install Firefox from .deb instead of Snap on Ubuntu
  include_tasks: firefox.yml
  when: (ansible_distribution == 'Ubuntu')

- name: "flatpak | force repair"
  shell: "/usr/bin/flatpak repair"

- name: "flatpak | install latest version of Kindle Comic Converter"
  flatpak:
    name: io.github.ciromattia.kcc
    state: present
    remote: flathub
  register: install_kcc
  until: install_kcc is not failed
  retries: 5

- name: "flatpak | install latest version of Anki"
  flatpak:
    name: net.ankiweb.Anki
    state: present
    remote: flathub
  register: install_anki
  until: install_anki is not failed
  retries: 5

- name: "flatpak | install latest version of Signal"
  flatpak:
    name: org.signal.Signal
    state: present
    remote: flathub
  register: install_signal
  until: install_signal is not failed
  retries: 5

- name: "flatpak | install latest version of Plex"
  flatpak:
    name: tv.plex.PlexDesktop
    state: present
    remote: flathub
  register: install_plex
  until: install_plex is not failed
  retries: 5

- name: "flatpak | install latest version of Jellyfin"
  flatpak:
    name: com.github.iwalton3.jellyfin-media-player
    state: present
    remote: flathub
  register: install_jellyfin
  until: install_jellyfin is not failed
  retries: 5
