---
- name: install latest version of i3 window manager
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - i3
    - i3lock
    - i3status

- name: Install latest version of Simplenote using APT
  include: simplenote-apt.yml
  when: ansible_pkg_mgr == 'apt'

- name: Install latest version of Simplenote using source
  include: simplenote-source.yml
  when: ansible_pkg_mgr != 'apt'

- name: Install latest version of Atom editor using APT
  include: atom-apt.yml
  when: ansible_pkg_mgr == 'apt'

- name: Install latest version of Atom editor using DNF
  include: atom-dnf.yml
  when: ansible_pkg_mgr == 'dnf'

- name: Install latest version of Atom editor using YUM
  include: atom-yum.yml
  when: ansible_pkg_mgr == 'yum'
