---
- name: include simplenote variables and defaults
  include_vars:
    file: "{{ item }}"
  with_items:
    - ../vars/simplenote.yml
    - ../defaults/simplenote.yml

- name: install latest version of i3 window manager
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - i3
    - i3lock
    - i3status
    - dmenu
    - dunst

- name: Ensures ~/.config/i3 exists
  file: path=/home/james/.config/i3/ state=directory recurse=yes
- name: Setup i3 config
  template:
    src: i3_config.j2
    dest: /home/james/.config/i3/config
    owner: james
    group: james
    mode: 0644
    validate: /usr/bin/i3 -c %s -C

- name: Ensures ~/.config/dunst exists
  file: path=/home/james/.config/dunst/ state=directory recurse=yes
- name: Setup dunst config
  template:
    src: dunstrc.j2
    dest: /home/james/.config/dunst/dunstrc
    owner: james
    group: james
    mode: 0644

- name: Setup Xdefaults config
  template:
    src: Xdefaults.j2
    dest: /home/james/.Xdefaults
    owner: james
    group: james
    mode: 0644

- name: Install latest version of CA certificates
  package:
    name: ca-certificates
    state: latest

- name: Install latest version of Atom editor using APT
  include: atom-apt.yml
  when: ansible_pkg_mgr == 'apt'

- name: Install latest version of Atom editor using DNF
  include: atom-dnf.yml
  when: ansible_pkg_mgr == 'dnf'

- name: Install latest version of Atom editor using YUM
  include: atom-yum.yml
  when: ansible_pkg_mgr == 'yum'

- name: Install latest version of Simplenote for Debian-based systems
  apt:
    deb:  https://github.com/Automattic/simplenote-electron/releases/download/v{{ simplenote_version }}/simplenote-{{ simplenote_version }}.deb
    state: present
  when: ansible_os_family == 'Debian'

- name: Install latest version of Simplenote for RedHat-based systems
  include: simplenote-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Setup shortcut for Simplenote
  template:
    src: simplenote_shortcut.j2
    dest: /usr/share/applications/Simplenote.desktop
    owner: root
    group: root
    mode: 0744

- name: Setup path for Simplenote
  blockinfile:
    path: /usr/local/bin/simplenote
    create: yes
    state: present
    content: |
      /opt/Simplenote-linux-x64/Simplenote $@ > /dev/null 2>&1 &
