---
- name: Ensures ~/.config exists
  file:
    path: /home/james/.config/
    state: directory
    recurse: true

- name: Install latest version of xournal PDF editor
  package:
    name: xournal
    state: latest

- name: Install latest version of Terminator
  package:
    name: terminator
    state: latest

- name: Ensures ~/.config/terminator exists
  file:
    path: /home/james/.config/terminator
    state: directory
    recurse: true

- name: lay out Terminator config file
  template:
    src: terminator.conf.j2
    dest: /home/james/.config/terminator/config
    owner: james
    group: james
    mode: 0644

- name: Install latest version of Calibre
  package:
    name: calibre
    state: latest

- name: Install latest version of CA certificates
  package:
    name: ca-certificates
    state: latest

# available in default Fedora repos
- name: Install latest version of GPXSee
  package:
    name: gpxsee
    state: latest
  when: ansible_distribution == 'Fedora'

- name: Install and configure Sensors
  include: sensors.yml

- name: Install Simplenote
  include: simplenote.yml

- name: Install Slack
  include: slack.yml

- name: Install Zoom
  include: zoom.yml

- name: Install Speedcrunch
  include: speedcrunch.yml
