---
- name: Install latest version of remmina RDP client
  package:
    name: remmina
    state: latest

- name: Install latest version of CA certificates
  package:
    name: ca-certificates
    state: latest

- name: Install Simplenote
  include: simplenote.yml

- name: Install Slack
  include: slack.yml
