---
- name: include simplenote defaults
  include_vars:
    file: ../defaults/simplenote.yml

- name: Install latest version of remmina RDP client
  package:
    name: remmina
    state: latest

- name: Install latest version of CA certificates
  package:
    name: ca-certificates
    state: latest

- name: Install latest version of Simplenote for Debian-based systems
  apt:
    deb:  https://github.com/Automattic/simplenote-electron/releases/download/v{{ simplenote_version }}/Simplenote-linux-{{ simplenote_version }}_amd64.deb
    state: latest
  when: ansible_os_family == 'Debian'

- name: Install latest version of Simplenote using DNF
  dnf:
    name: https://github.com/Automattic/simplenote-electron/releases/download/v{{ simplenote_version }}/Simplenote-linux-{{ simplenote_version }}-x86_64.rpm
    state: latest
  when: ansible_pkg_mgr == 'dnf'

- name: Install latest version of Simplenote using YUM
  yum:
    name: https://github.com/Automattic/simplenote-electron/releases/download/v{{ simplenote_version }}/Simplenote-linux-{{ simplenote_version }}-x86_64.rpm
    state: latest
  when: ansible_pkg_mgr == 'yum'
