---
- name: install latest Simplenote from GitHub releases
  import_role:
    name: github-releases
  vars:
    org: Automattic
    repo: simplenote-electron
    filename: Simplenote-linux
    arch: x86_64
    version: latest
    project_url: https://api.github.com/repos/{{ org }}/{{ repo }}/releases
  tags: gh-releases
