---
- name: include Slack defaults for Debian-based
  include_vars:
    file: ../defaults/slack-Debian.yml
  when: ansible_os_family == 'Debian'

- name: add apt repo gpg key for Slack
  apt_key:
    url: "{{ apt_slack_repo_key }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: add apt repo for Slack
  apt_repository:
    repo: "{{ apt_slack_repo }}"
    mode: 0644
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: include Slack defaults for RedHat-based
  include_vars:
    file: ../defaults/slack-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: add yum repo for Slack
  yum_repository:
    name: slacktechnologies_slack
    description: "Slack Repository from packagecloud.io"
    baseurl: https://packagecloud.io/slacktechnologies/slack/fedora/21/$basearch
    gpgkey: https://packagecloud.io/slacktechnologies/slack/gpgkey
    gpgcheck: no
    repo_gpgcheck: yes
    enabled: yes
  when: ansible_os_family == 'RedHat'

- name: install Slack package
  package:
    name: "{{ slack_package_name }}"
    state: present
