---
- name: install fail2ban
  package:
    name: fail2ban
    state: latest

- name: update configuration file - /etc/fail2ban/fail2ban.local
  template:
    src: fail2ban.local.j2
    dest: /etc/fail2ban/fail2ban.local
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban

- name: update configuration file - /etc/fail2ban/jail.local
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban

- name: setup geosshdeny filter
  template:
    src: geosshdeny_filter.conf.j2
    dest: /etc/fail2ban/filter.d/geosshdeny.conf
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban

- name: setup geosshdeny action
  template:
    src: geosshdeny_action.conf.j2
    dest: /etc/fail2ban/action.d/geosshdeny.conf
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban

- name: copy jails
  copy:
    src: "{{ fail2ban_jaild_path }}"
    dest: /etc/fail2ban/jail.d/
    owner: root
    group: root
    mode: 0644
  when: fail2ban_jaild_path is defined
  notify: restart fail2ban

- name: install geoip
  package:
    name: geoip
    state: latest

- name: start and enable service
  service:
    name: fail2ban
    state: started
    enabled: true
