---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"
      skip: true
  when: (geoip_package_name is not defined)

- name: install fail2ban
  package:
    name: fail2ban
    state: latest

- name: update configuration file - /etc/fail2ban/fail2ban.local
  template:
    src: fail2ban.local.j2
    dest: /etc/fail2ban/fail2ban.local
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban

- name: update configuration file - /etc/fail2ban/jail.local
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban

- name: setup geosshdeny filter
  template:
    src: geosshdeny_filter.conf.j2
    dest: /etc/fail2ban/filter.d/geosshdeny.conf
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban

- name: setup geosshdeny action
  template:
    src: geosshdeny_action.conf.j2
    dest: /etc/fail2ban/action.d/geosshdeny.conf
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban

- name: copy jails
  copy:
    src: "{{ fail2ban_jaild_path }}"
    dest: /etc/fail2ban/jail.d/
    owner: root
    group: root
    mode: 0644
  when: fail2ban_jaild_path is defined
  notify: restart fail2ban

- name: install geoip
  package:
    name: "{{ geoip_package_name }}"
    state: latest

- name: make logging directory
  file:
    state: directory
    path: /var/log/fail2ban
    owner: root
    group: root
    mode: 0750

- name: touch log files
  file:
    state: touch
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0744
  with_items:
    - "{{ fail2ban_logtarget }}"
    - "{{ fail2ban_geosshdeny_jail_logtarget }}"

- name: start and enable service
  service:
    name: fail2ban
    state: started
    enabled: true
  notify: fail2ban status
