---
- name: Ensure firewalld is installed.
  package:
    name: firewalld
    state: latest

# to work around bug https://github.com/saltstack/salt/issues/55110
- name: Update the repository cache and update package "iptables" to latest version using default release buster-backports
  apt:
    name: iptables
    state: latest
    default_release: buster-backports
    update_cache: true
  when: (ansible_distribution == 'Debian' and ansible_distribution_major_version is version(10, 'eq'))

- name: Ensure firewalld Python 3 bindings are installed
  package:
    name: python3-firewall
    state: latest
  when: (ansible_distribution != 'Debian' and ansible_distribution_major_version is not version(10, 'eq'))

- name: Start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: true

- name: configure firewall zones
  include_tasks: firewall-zones.yml

- name: configure common firewall rules
  include_tasks: firewall-rules-common.yml

- name: disable other firewalls
  include_tasks: disable-other-firewalls.yml
  when: (firewall_disable_iptables or firewall_disable_ufw)
