---
- name: Ensure firewalld is installed.
  package:
    name: firewalld
    state: latest

- name: Ensure firewalld Python 3 bindings are installed
  package:
    name: python3-firewall
    state: latest

- name: Start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: true

- name: configure common firewall rules
  include_tasks: firewall-rules-common.yml

- name: disable other firewalls
  include_tasks: disable-other-firewalls.yml
  when: (firewall_disable_iptables or firewall_disable_ufw)
