---
- name: install fedy repo
  get_url:
    url: "https://copr.fedorainfracloud.org/coprs/kwizart/fedy/repo/fedora-{{ ansible_distribution_version }}/kwizart-fedy-fedora-{{ ansible_distribution_version }}.repo"
    dest: /etc/yum.repos.d/fedy.repo
    owner: root
    group: root
    mode: '0644'

- name: install fedy
  package:
    name: fedy
    state: latest
