---
- name: install fedy repo package
  dnf:
    name: https://dl.folkswithhats.org/fedora/{{ ansible_distribution_major_version|int }}/RPMS/folkswithhats-release.noarch.rpm
    state: latest

- name: install fedy
  package:
    name: fedy
    state: latest
