---
- name: "flatpak | force repair"
  shell: "/usr/bin/flatpak repair"

- name: install gnome-tweak-tool
  package:
    name: gnome-tweaks
    state: latest

- name: "flatpak | install latest version of Gnome Extensions"
  flatpak:
    name: org.gnome.Extensions
    state: present
  register: install_extensions
  until: install_extensions is not failed
  retries: 5

- name: Include repo-extra for Fedora as pre-requisite for Fedy
  include_role:
    name: repo-extra
  when: (ansible_pkg_mgr == 'dnf') and (ansible_distribution == 'Fedora')

- name: Install latest version of Fedy on Fedora using DNF
  include_tasks: fedy.yml
  when: (ansible_pkg_mgr == 'dnf') and (ansible_distribution == 'Fedora')

# eventually more distros will change package name, see
# https://repology.org/project/gnome-browser-connector/versions
- name: Install Gnome Shell Extensions integration for web browsers
  package:
    name: gnome-browser-connector
    state: latest
  when: ansible_distribution != 'Ubuntu'

- name: Install dconf binary
  package:
    name: dconf-cli
    state: latest
  when: ansible_os_family == 'Debian'
