---
- name: install gnome-tweak-tool
  package:
    name: gnome-tweak-tool
    state: latest

- name: Install latest version of Fedy on Fedora using DNF
  include: fedy.yml
  when: (ansible_pkg_mgr == 'dnf') and (ansible_distribution == 'Fedora')

- name: Install Gnome Shell Extensions installer/integration for web browsers
  package:
    name: chrome-gnome-shell
    state: latest

- name: Ensures ~/.config exists
  file: path=/home/james/.config/ state=directory recurse=yes
- name: Temporarily store Gnome settings in ~/.config/
  template:
    src: gnome_settings.j2
    dest: /home/james/.config/gnome_settings.conf
    owner: james
    group: james
    mode: 0644

- name: Configure keyboard shortcuts in Gnome
  command: dconf load /org/gnome/ < /home/james/.config/gnome_settings.conf
