---
- name: install gnome metapackage when running tests in ci
  package:
    name:
      - gnome-session
      - gdm3
    state: latest
  when: ansible_distribution == 'Ubuntu'

- include_tasks: remove_bloat.yml
- include_tasks: install_packages.yml
- include_tasks: gnome_extensions.yml
  args:
    apply:
      become: true
      become_user: james
  tags: ci

- name: lay out mimeapps.list (default applications)
  copy:
    src: mimeapps.list
    dest: /home/james/.config/mimeapps.list
    owner: james
    group: james
    mode: 0600
  tags: ci

- name: install psutil Python package
  package:
    name: python3-psutil
    state: latest

- name: Modify application settings using dconf
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  become: true
  become_user: "{{ gnome_user }}"
  loop: "{{ gnome_dconf }}"
  tags: ci
