---
- name: install the latest versions of Ansible
  package:
    name: ansible
    state: latest

- name: install the latest version of Ansible-Lint
  pip:
    name: ansible-lint
    state: latest
  become: True

- name: install the latest version of Ansible-Review
  pip:
    name: ansible-review
    state: latest
  become: True
