---
- name: restart docker
  service: "name=docker state={{ docker_restart_handler_state }}"
  when: (ansible_service_mgr == "systemd") or (ansible_service_mgr == "upstart")

- name: restart firewalld
  service:
    name: firewalld
    state: restarted
