---
- name: Install homebrew
  include_tasks: homebrew.yml

- name: install applications via MacOS App Store
  include_tasks: mas.yml

- name: enable startup chime
  # https://mrmacintosh.com/how-to-enable-the-mac-startup-chime-on-your-2016-macbook-pro/
  shell: nvram StartupMute=%00

- name: install llm plugins
  command: "llm install {{ item }}"
  with_items:
    - llm-anthropic
    - llm-gemini
    - llm-ollama
    - llm-commit

- name: install sncli with uv
  command: "uv tool install sncli --python=3.11"
