---
- name: Determine Homebrew ownership variables
  set_fact:
    homebrew_user: '{{ homebrew_user | default(ansible_user_id) }}'
    homebrew_group: '{{ homebrew_group | default(ansible_user_gid) }}'

- name: import work-related defaults if tagged work
  include_vars:
    file: ../defaults/work.yml

- block:
  # taps work.
  - name: Ensure configured work-related taps are tapped.
    homebrew_tap:
      tap: '{{ item.name | default(item) }}'
      url: '{{ item.url | default(omit) }}'
      state: present
    loop: "{{ homebrew_taps_work }}"
    become_user: "{{ homebrew_user }}"
    ignore_errors: true

  # Cask work.
  - name: Install configured work-related cask applications.
    homebrew_cask:
      name: "{{ item.name | default(item) }}"
      state: present
      install_options: "{{ item.install_options | default('appdir=' + homebrew_cask_appdir) }}"
      accept_external_apps: "{{ homebrew_cask_accept_external_apps }}"
    loop: "{{ homebrew_cask_apps_work }}"
    become_user: "{{ homebrew_user }}"
    ignore_errors: true

  # Brew.
  - name: Ensure configured work-related homebrew packages are installed.
    homebrew:
      name: "{{ item.name | default(item) }}"
      install_options: "{{ item.install_options | default(omit) }}"
      state: present
    loop: "{{ homebrew_installed_packages_work }}"
    become_user: "{{ homebrew_user }}"
    ignore_errors: true
