---
# include Debian vars so that ansible_dsitribution_release is properly set for Debian Testing Buster/Sid
- include_vars: "../vars/Debian.yml"
  when: ansible_distribution == 'Debian'

- name: Add Dropbox KeyServer
  apt_key:
    keyserver: pgp.mit.edu
    id: 1C61A2656FB57B7E4DE0F4C1FC918B335044912E
    state: present

- name: Add Dropbox PPA Repo
  apt_repository:
    repo: 'deb http://linux.dropbox.com/{{ansible_distribution|lower}} {{ansible_distribution_release}} main'

- name: Install Dropbox
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  with_items:
    - dropbox
    - python-gpgme
