---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"
    - skip: true
  when: (python_gpg_package_name is not defined)

- name: Add Dropbox KeyServer
  apt_key:
    keyserver: pgp.mit.edu
    id: 1C61A2656FB57B7E4DE0F4C1FC918B335044912E
    state: present

- name: Add Dropbox PPA Repo
  apt_repository:
    repo: 'deb http://linux.dropbox.com/{{ansible_distribution|lower}} {{ansible_distribution_release}} main'

- name: Install Python GPG
  apt:
    name: "{{ python_gpg_package_name }}"
    state: latest
    update_cache: yes

- name: Install Dropbox
  apt:
    name: dropbox
    state: latest
