---
- name: install latest version of Libre Office
  package:
    name: libreoffice
    state: latest

- name: install latest version of LyX
  package:
    name: lyx
    state: latest

- name: install latest version of TexLive
  package:
    name: texlive
    state: latest

- name: install latest version of LaTex MK
  package:
    name: latexmk
    state: latest

- name: install moderncv package and dependencies for LaTeX
  package:
    name:
      - texlive-moderncv
      - texlive-fontawesome5
      - texlive-multirow
      - texlive-arydshln
    state: latest
  when: ansible_distribution == 'Fedora'
