---
- name: install dev Kubernetes environment on Linux
  include: linux.yml
  when: ansible_os_family != 'Darwin'

- name: install dev Kubernetes environment on MacOS
  include: mac.yml
  when: ansible_os_family == 'Darwin'
