---
- name: install dev Kubernetes environment on Linux
  include_tasks: linux.yml
  when: ansible_os_family != 'Darwin'

- name: install dev Kubernetes environment on MacOS
  include_tasks: mac.yml
  when: ansible_os_family == 'Darwin'
