---
- name: Add Atom apt key.
  apt_key:
    url: https://packagecloud.io/AtomEditor/atom/gpgkey
    id: 4C6E74D6C0A35108
    state: present
  register: add_repository_key
  ignore_errors: "{{ docker_apt_ignore_key_error }}"

- name: Ensure curl is present (on older systems without SNI).
  package: name=curl state=present
  when: add_repository_key is failed

- name: Add Atom apt key (alternative for older systems without SNI).
  shell: "curl -sSL https://packagecloud.io/AtomEditor/atom/gpgkey | sudo apt-key add -"
  args:
    warn: false
  when: add_repository_key is failed

- name: Add repository for Atom editor
  apt_repository:
    repo: "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main"
    state: present
    filename: atom

- name: install latest version of Atom editor via APT
  apt:
    name: atom
    state: latest
