---
- name: Add repository for Atom editor
  apt_repository:
    repo: 'ppa:webupd8team/atom'

- name: "apt | update cache"
  apt:
    update_cache: yes

- name: install latest version of Atom editor via APT
  apt:
    name: atom
    state: latest
