---
- name: add Atom repository
  yum_repository:
    name: atom
    description: Atom.io editor repository
    baseurl: https://packagecloud.io/AtomEditor/atom/el/7/$basearch/
    gpgcheck: yes
    gpgkey: https://packagecloud.io/AtomEditor/atom/gpgkey
    enabled: yes

- name: install latest version of Atom editor via YUM
  yum:
    name: atom
    state: present
