---
- name: Install latest version of DBeaver using APT
  include_tasks: dbeaver-apt.yml
  when: ansible_pkg_mgr == 'apt'
  tags: gui

- name: Install latest version of DBeaver using DNF
  include_tasks: dbeaver-dnf.yml
  when: ansible_pkg_mgr == 'dnf'
  tags: gui

- name: Install latest version of DBeaver using YUM
  include_tasks: dbeaver-yum.yml
  when: ansible_pkg_mgr == 'yum'
  tags: gui

- name: Install latest version of vscode editor using APT
  include_tasks: vscode-apt.yml
  when: ansible_pkg_mgr == 'apt'
  tags: gui

- name: Install latest version of vscode editor using DNF
  include_tasks: vscode-dnf.yml
  when: ansible_pkg_mgr == 'dnf'
  tags: gui

- name: Install latest version of vscode editor using YUM
  include_tasks: vscode-yum.yml
  when: ansible_pkg_mgr == 'yum'
  tags: gui

- name: Install Zeal docs tool
  package:
    name: zeal
    state: latest

- name: "flatpak | install the latest version of Postman"
  flatpak:
    name: com.getpostman.Postman
    state: present
  register: install_postman
  until: install_postman is not failed
  retries: 5

- name: Install g++ as pre-req for neovim
  package:
    name: g++
    state: latest

- name: Install neovim
  package:
    name: neovim
    state: latest

- name: confirm neovimfiles repo exists
  stat:
    path: "{{ home_dir_path }}/.config/nvim"
  register: neovimfiles_repo

- name: clone neovimfiles from github
  git:
    repo: 'https://github.com/toozej/neovimfiles.git'
    accept_hostkey: true
    dest: "{{ home_dir_path }}/.config/nvim"
    recursive: true
  register: clone_or_pull
  when: (not ansible_check_mode) and (not neovimfiles_repo.stat.exists)

- name: setup neovimfiles
  raw: "sudo -u {{ james_user }} {{ home_dir_path|quote }}/.config/nvim/setup.sh"
  when: (clone_or_pull.changed == true) and (not ansible_check_mode)
  tags: ci
