---
- name: Install latest version of DBeaver using APT
  include_tasks: dbeaver-apt.yml
  when: ansible_pkg_mgr == 'apt'
  tags: gui

- name: Install latest version of DBeaver using DNF
  include_tasks: dbeaver-dnf.yml
  when: ansible_pkg_mgr == 'dnf'
  tags: gui

- name: Install latest version of DBeaver using YUM
  include_tasks: dbeaver-yum.yml
  when: ansible_pkg_mgr == 'yum'
  tags: gui

- name: Install latest version of vscode editor using APT
  include_tasks: vscode-apt.yml
  when: ansible_pkg_mgr == 'apt'
  tags: gui

- name: Install latest version of vscode editor using DNF
  include_tasks: vscode-dnf.yml
  when: ansible_pkg_mgr == 'dnf'
  tags: gui

- name: Install latest version of vscode editor using YUM
  include_tasks: vscode-yum.yml
  when: ansible_pkg_mgr == 'yum'
  tags: gui
