---
- name: add vscode repository
  yum_repository:
    name: vscode
    description: vscode repository
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    enabled: true

- name: install latest version of vscode editor via Yum
  yum:
    name: code
    state: present
