---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"
      skip: True
      when: (zabbix_agent_package_name is not defined)

- name: install latest zabbix agent package
  package:
    name: "{{ zabbix_agent_package_name }}"
    state: latest

- name: copy zabbix_agent.conf to /etc/zabbix/zabbix_agentd.conf
  template:
    src: zabbix_agent.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: 0644
    notify: start and enable zabbix-agent service
