---
- name: install latest version of flatpak package
  package:
    name: flatpak
    state: latest

- name: Remove Fedora third-party filtered flathub remote
  flatpak_remote:
    name: flathub
    state: absent

- name: Add the flathub flatpak repository remote
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
