---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"
      skip: true
  when: (powerline_fonts_package_name is not defined) or (sensors_package_name is not defined)

# set trackpad to reverse scrolling

# set trackpad to tap to click

# set keyboard shortcuts

# install thunar smb support packages
- name: install Thunar SMB support packages
  package:
    name:
      - thunar-shares-plugin
      - gvfs-smb
    state: latest
# set wallpaper
# create one lower XFCE panel with Windows-like setup
# set XFCE panel to autohide
