---
homebrew_installed_packages_work:
  - autoconf
  - awscli
  - bfg
  - circleci
  - coreutils
  - dive
  - fx
  - gnu-sed
  - go
  - graphviz
  - helm
  - ipcalc
  - jfrog-cli
  - kpcli
  - kubernetes-cli
  - minikube
  - node
  - packer
  - pipenv
  - plantuml
  - postgresql
  - pre-commit
  - prettier
  - pyenv
  - rbenv
  - terraform
  - terraform-docs
  - terraform-inventory
  - terragrunt
  - tfenv
  - tflint
  - vault
  - vmware-tanzu/varvel/ytt
  - yamllint

homebrew_cask_apps_work:
  - apache-directory-studio
  - beyond-compare
  - bruno
  - dbeaver-community
  - pycharm-ce
  - utc-menu-clock
  - xmind
