---

homebrew_taps_work:
  - carvel-dev/carvel

homebrew_installed_packages_work:
  - autoconf
  - awscli
  - bfg
  - circleci
  - coreutils
  - dive
  - fx
  - gnu-sed
  - go
  - graphviz
  - helm
  - ipcalc
  - jfrog-cli
  - kpcli
  - kubernetes-cli
  - minikube
  - node
  - packer
  - pipenv
  - plantuml
  - postgresql
  - pre-commit
  - prettier
  - pyenv
  - rbenv
  # knowingly out of order
  - tfenv
  - terragrunt
  - tflint
  - vault
  - ytt
  - yamllint

homebrew_cask_apps_work:
  - apache-directory-studio
  - insomnium
  - dbeaver-community
  - goland
  - rancher
  - pycharm-ce
  - utc-menu-clock
  - utm
  - vagrant
  - xmind
