---
# defaults write com.apple.screensaver askForPassword -int 1
- name: Ask for a password on screensaver ASAP part 1
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: askForPassword
    type: int
    value: 1
    state: present
  become: true
  notify:
    - restart Dock
    - restart Finder
# defaults write com.apple.screensaver askForPasswordDelay -int 0
- name: Ask for a password on screensaver ASAP part 2
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: askForPasswordDelay
    type: int
    value: 0
    state: present
  become: true
  notify:
    - restart Dock
    - restart Finder

# defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool false
- name: Do not show icons for hard drives on desktop
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowExternalHardDrivesOnDesktop
    type: bool
    value: false
    state: present
  notify:
    - restart Dock
    - restart Finder

# defaults write com.apple.finder ShowMountedServersOnDesktop -bool false
- name: Do not show icons for servers on desktop
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowMountedServersOnDesktop
    type: bool
    value: false
    state: present
  notify:
    - restart Dock
    - restart Finder

# defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool false
- name: Do not show icons for removable media on desktop
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowRemovableMediaOnDesktop
    type: bool
    value: false
    state: present
  notify:
    - restart Dock
    - restart Finder

# defaults write com.apple.finder ShowRecentTags -int 0
- name: Disable Finder tags on left sidebar
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowRecentTags
    type: int
    value: 0
    state: present
  notify:
    - restart Dock
    - restart Finder

# defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
- name: Disable the warning when changing a file extension
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false
    state: present
  notify:
    - restart Dock
    - restart Finder

# defaults write com.apple.finder NewWindowTarget PfHm
- name: New Finder Window shows your home folder part 1
  community.general.osx_defaults:
    domain: com.apple.finder
    key: NewWindowTarget
    type: string
    value: PfHm
    state: present
  notify:
    - restart Dock
    - restart Finder
# defaults write com.apple.finder NewWindowTargetPath "file:///Users/{{ username }}/"
- name: New Finder Window shows your home folder part 2
  community.general.osx_defaults:
    domain: com.apple.finder
    key: NewWindowTargetPath
    type: string
    value: "{{ homebrew_user }}"
    state: present
  notify:
    - restart Dock
    - restart Finder

# defaults write NSGlobalDomain AppleShowAllExtensions -bool true
- name: Show all filename extensions.
  community.general.osx_defaults:
    key: AppleShowAllExtensions
    type: bool
    value: true
    state: present
  notify:
    - restart Dock
    - restart Finder

# defaults write com.apple.dock autohide -bool true
- name: Automatically hide and show the Dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true
    state: present
  notify:
    - restart Dock
    - restart Finder

# defaults write com.apple.dock orientation -string left
- name: Dock on Left side
  community.general.osx_defaults:
    domain: com.apple.dock
    key: orientation
    type: string
    value: left
    state: present
  notify:
    - restart Dock
    - restart Finder

# defaults write com.apple.dock show-recents -int 0
- name: Dock disable show recent apps
  community.general.osx_defaults:
    domain: com.apple.dock
    key: show-recents
    type: int
    value: 0
    state: present
  notify:
    - restart Dock
    - restart Finder

# defaults write NSGlobalDomain _HIHideMenuBar -bool true
- name: Auto-hide top menu bar
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: _HIHideMenuBar
    type: bool
    value: true
    state: present
  notify:
    - restart Dock
    - restart Finder

# defaults write com.apple.dock wvous-tl-corner -int 5
- name: Set Top Left screen corner - Start screen saver part 1
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-tl-corner
    type: int
    value: 5
    state: present
  notify:
    - restart Dock
    - restart Finder
# defaults write com.apple.dock wvous-tl-modifier -int 0
- name: Set Top Left screen corner - Start screen saver part 2
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-tl-modifier
    type: int
    value: 0
    state: present
  notify:
    - restart Dock
    - restart Finder

# defaults write com.apple.dock wvous-tr-corner -int 0
- name: Set Top Right screen corner - Mission Control part 1
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-tr-corner
    type: int
    value: 0
    state: present
  notify:
    - restart Dock
    - restart Finder
# defaults write com.apple.dock wvous-tr-modifier -int 0
- name: Set Top Right screen corner - Mission Control part 2
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-tr-modifier
    type: int
    value: 0
    state: present
  notify:
    - restart Dock
    - restart Finder

# defaults write com.apple.dock wvous-bl-corner -int 2
- name: Set Bottom Left screen corner - Show Desktop part 1
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-bl-corner
    type: int
    value: 2
    state: present
  notify:
    - restart Dock
    - restart Finder
# defaults write com.apple.dock wvous-bl-modifier -int 0
- name: Set Bottom Left screen corner - Show Desktop part 2
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-bl-modifier
    type: int
    value: 0
    state: present
  notify:
    - restart Dock
    - restart Finder

# defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
- name: Expand save panels by default part 1
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: true
    state: present
  notify:
    - restart Dock
    - restart Finder
# defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true
- name: Expand save panels by default part 2
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode2
    type: bool
    value: true
    state: present
  notify:
    - restart Dock
    - restart Finder

# defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
- name: Disable automatic spelling correction
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false
    state: present
  notify:
    - restart Dock
    - restart Finder
# defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false
- name: Disable automatic capitalization correction
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticCapitalizationEnabled
    type: bool
    value: false
    state: present
  notify:
    - restart Dock
    - restart Finder
# defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
- name: Disable automatic quote substitution
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: false
    state: present
  notify:
    - restart Dock
    - restart Finder
# defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false
- name: Disable automatic dash substitution
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticDashSubstitutionEnabled
    type: bool
    value: false
    state: present
  notify:
    - restart Dock
    - restart Finder

# defaults write com.apple.ActivityMonitor ShowCategory -int 0
- name: Show all processes in Activity Monitor
  community.general.osx_defaults:
    domain: com.apple.ActivityMonitor
    key: ShowCategory
    type: int
    value: 0
    state: present
  notify:
    - restart Dock
    - restart Finder

# defaults write com.apple.ActivityMonitor SortColumn -string "CPUUsage"
- name: Sort Activity Monitor results by CPU usage
  community.general.osx_defaults:
    domain: com.apple.ActivityMonitor
    key: SortColumn
    type: string
    value: "CPUUsage"
    state: present
# defaults write com.apple.ActivityMonitor SortDirection -int 0
- name: Sort Activity Monitor results by CPU usage descending
  community.general.osx_defaults:
    domain: com.apple.ActivityMonitor
    key: SortDirection
    type: int
    value: 0
    state: present

# defaults write com.apple.TextEdit RichText -int 0
- name: Use plain text mode for new TextEdit documents
  community.general.osx_defaults:
    domain: com.apple.TextEdit
    key: RichText
    type: int
    value: 0
    state: present

# defaults write com.apple.TextEdit PlainTextEncoding -int 4
- name: Open and save files as UTF-8 in TextEdit part 1
  community.general.osx_defaults:
    domain: com.apple.TextEdit
    key: PlainTextEncoding
    type: int
    value: 4
    state: present
# defaults write com.apple.TextEdit PlainTextEncodingForWrite -int 4
- name: Open and save files as UTF-8 in TextEdit part 2
  community.general.osx_defaults:
    domain: com.apple.TextEdit
    key: PlainTextEncodingForWrite
    type: int
    value: 4
    state: present

# defaults write com.apple.assistant.support "Assistant Enabled" -bool false
- name: Disable Siri
  community.general.osx_defaults:
    domain: com.apple.assistant.support
    key: "Assistant Enabled"
    type: bool
    value: false
    state: present

# Additional preferences to select:
# sys prefs -> general -> auto appearance
#   multi colour accent
#   highlight colour accent colour
#   uncheck close windows when quitting an app
# sys prefs -> desktop and dock
#   make Firefox the default browser
# sys prefs -> desktop and dock -> mission control
#   uncheck automatiically rearrange spaces based on most recent use
# sys prefs -> keyboard -> keyboard shortcuts -> mission control
#   mission control -> move left a space set to shift+command+left
#   mission control -> move right a space set to shift+command+right
# sys prefs -> control center -> menu bar only
#   always hide and show menu bar = always
#   spotlight = don't show in menu bar
