---
- name: Install homebrew
  include_tasks: homebrew.yml

- name: Configure MacOS Defaults
  include_tasks: macos-defaults.yml

- name: install applications via MacOS App Store
  include_tasks: mas.yml

- name: setup PyCharm helper script
  copy:
    src: pycharm-helper
    dest: /usr/local/bin/pycharm
    owner: "{{ homebrew_user }}"
    group: "{{ homebrew_group }}"
    mode: 0644
