---
#- name: Install homebrew
#  include: homebrew.yml
#
#- name: Install MacOS Packages via Pip
#  pip:
#    name: virtualenv
#    state: latest

- name: Configure MacOS Defaults
  include: macos-defaults.yml
