---
- name: Install homebrew
  include_tasks: homebrew.yml

- name: Configure MacOS Defaults
  include_tasks: macos-defaults.yml

- name: setup PyCharm helper script
  copy:
    src: pycharm-helper
    dest: /usr/local/bin/pycharm
    owner: "{{ homebrew_user }}"
    group: "{{ homebrew_group }}"
    mode: 0644

# additional manual things to install via MacOS app store
# - somafm radio player
# - MS Remote Desktop
