---
- name: disable enhanced retransmission mode (ERTM) for bluetooth xbox controller
  copy:
    src: "files/xbox_bt.conf"
    dest: "/etc/modprobe.d/xbox_bt.conf"
    owner: root
    group: root
    mode: "0644"

- name: set selinux context for xbox_bt.conf if using selinux
  file:
    path: "/etc/modprobe.d/xbox_bt.conf"
    seuser: "system_u"
    serole: "object_r"
    setype: "modules_conf_t"
    selevel: "s0"
  when: (ansible_selinux is defined and ansible_selinux != false and ansible_selinux.status == 'enabled')

- name: "flatpak | install the latest version of Steam"
  flatpak:
    name: com.valvesoftware.Steam
    state: present
  register: install_steam
  until: install_steam is not failed
  retries: 5

- name: "flatpak | install the latest version of Steam Link"
  flatpak:
    name: com.valvesoftware.SteamLink
    state: present
  register: install_steam_link
  until: install_steam_link is not failed
  retries: 5

- name: "apt | pre-requisites for installing Lutris on Debian"
  include: lutris-debian.yml
  when: (ansible_distribution == 'Debian')

- name: "apt | pre-requisites for installing Lutris on Ubuntu "
  include: lutris-ubuntu.yml
  when: (ansible_distribution == 'Ubuntu')

- name: install latest version of Lutris
  package:
    name: lutris
    state: latest
  when: (ansible_distribution != 'CentOS')

- name: install latest version of Mumble
  package:
    name: mumble
    state: latest
  when: (ansible_distribution != 'CentOS')

- name: install latest version of Corectrl
  package:
    name: corectrl
    state: latest
  when: (ansible_distribution == 'Fedora')

- name: "flatpak | install latest version of Discord"
  flatpak:
    name: com.discordapp.Discord
    state: present
  register: install_discord
  until: install_discord is not failed
  retries: 5

- name: "flatpak | install latest version of RetroArch"
  flatpak:
    name: org.libretro.RetroArch
    state: present
  register: install_retroarch
  until: install_retroarch is not failed
  retries: 5

- name: "flatpak | install latest version of Athenaeum"
  flatpak:
    name: com.gitlab.librebob.Athenaeum
    state: present
  register: install_athenaeum
  until: install_athenaeum is not failed
  retries: 5

- name: "flatpak | install latest version of Yuzu"
  flatpak:
    name: org.yuzu_emu.yuzu
    state: present
  register: install_yuzu
  until: install_yuzu is not failed
  retries: 5
