---
- name: "flatpak | install the latest version of Steam"
  flatpak:
    name: com.valvesoftware.Steam
    state: present

- name: "apt | pre-requisites for installing Lutris on Debian"
  include: lutris-debian.yml
  when: (ansible_distribution == 'Debian')

- name: "apt | pre-requisites for installing Lutris on Ubuntu "
  include: lutris-ubuntu.yml
  when: (ansible_distribution == 'Ubuntu')

- name: install latest version of Lutris
  package:
    name: lutris
    state: latest
  when: (ansible_distribution != 'CentOS')
