---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"
  when: (steam_package_name is not defined)

- name: "dnf | setup Negativo Steam repo"
  include: steam-dnf.yml
  when: ansible_pkg_mgr == 'dnf'

- name: "yum | setup Negativo Steam repo"
  include: steam-yum.yml
  when: ansible_pkg_mgr == 'yum'

- name: "apt | pre-requisites for installing Steam"
  include: steam-apt.yml
  when: (ansible_distribution == 'Debian') or (ansible_distribution == 'Ubuntu')

- name: install the latest version of Steam
  package:
    name: "{{steam_package_name}}"
    state: latest
