---
- name: install 32-bit drivers for RHEL
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - libtxc
    - dxtn.x86_64

- name: "yum | ensure Negativo17.org Steam repo present for RHEL"
  command: yum-config-manager --add-repo=https://negativo17.org/repos/epel-steam.repo
  when: (ansible_distribution == 'Red Hat Enterprise Linux') or (ansible_distribution == 'CentOS')
