---
- name: "yum | ensure Negativo17.org Steam repo present for RHEL"
  yum:
    name: https://negativo17.org/repos/epel-steam.repo
    state: present
    enablerepo: True
    update_cache: True
  when: (ansible_distribution == 'Red Hat Enterprise Linux') or (ansible_distribution == 'CentOS')
