FROM centos:8

# update dnf and ensure pip is latest version
RUN dnf install -y python3 git python3-dnf sudo python3-pip && pip3 install --upgrade --force pip

# combat not having CA Certs installed
# specific version of urllib3 required by docker-py
RUN pip3 install pyopenssl ndg-httpsclient 'urllib3<1.25,>=1.21.1' pyasn1 requests

# setup the james user
RUN useradd -m -c "james" james -s /bin/bash

# install pre-reqs
ENV ANSIBLE_VERSION=latest
RUN if [ "$ANSIBLE_VERSION" = "latest" ]; then pip3 install ansible ansible-lint; else pip3 install ansible==$ANSIBLE_VERSION; fi

