FROM ubuntu:20.04

RUN export DEBIAN_FRONTEND=noninteractive && apt-get update -qq && apt-get install -y tzdata && ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime && dpkg-reconfigure --frontend noninteractive tzdata

# update apt and ensure pip is latest version
RUN apt-get update -qq && apt-get install lsb-release python3-pip git apt-transport-https software-properties-common debconf-utils sudo -y && pip3 install --upgrade --force pip

# combat not having CA Certs installed
# specific version of urllib3 required by docker-py
RUN pip3 install pyopenssl ndg-httpsclient 'urllib3<1.25,>=1.21.1' pyasn1 requests

# setup the james user
RUN useradd -m -c "james" james -s /bin/bash

# install pre-reqs
ENV ANSIBLE_VERSION=latest
RUN if [ "$ANSIBLE_VERSION" = "latest" ]; then pip3 install ansible ansible-lint; else pip3 install ansible==$ANSIBLE_VERSION; fi

