---
# Load a variable file based on the OS type, or a default if not found.
- name: Include vars and defaults
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int }}.yml"
        - "../vars/{{ ansible_distribution }}.yml"
        - "../vars/{{ ansible_os_family }}-{{ ansible_distribution_major_version | int }}.yml"
        - "../vars/{{ ansible_os_family }}.yml"
        - "../vars/default.yml"
      skip: true
  when: (libselinux_package_name is not defined)

- name: include RPMFusion repo on RedHat-based systems
  include_role:
    name: 'repo-extra'
  when: ansible_os_family == 'RedHat'

- name: install latest version of dnf-utils on DNF systems
  package:
    name: dnf-utils
    state: latest
  when: ansible_pkg_mgr == 'dnf'

- name: install apt-transport-https
  package:
    name: apt-transport-https
    state: present
  when: (ansible_pkg_mgr == 'apt')
