---
- name: include RPMFusion repo on RedHat-based systems
  include_role:
    name: 'repo-extra'
  when: ansible_os_family == 'RedHat'

- name: Import EPEL GPG key on RHEL-based systems
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
    state: present
  when: (ansible_distribution == 'Red Hat Enterprise Linux') or (ansible_distribution == 'CentOS')

- name: install the latest version of libselinux-python package on RedHat-based systems
  package:
    name: libselinux-python
    state: latest
  when: ansible_os_family == 'RedHat'

- name: install latest version of dnf-utils on DNF systems
  package:
    name: dnf-utils
    state: latest
  when: ansible_pkg_mgr == 'dnf'
