---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"
      skip: True
  when: (openjdk_package_name is not defined) or (openjre_package_name is not defined)

- name: install latest openjdk 11
  package:
    name: "{{ openjdk_package_name }}"
    state: latest

- name: install latest openjre 11
  package:
    name: "{{ openjre_package_name }}"
    state: latest
  when: ansible_os_family == "Debian"
