---
- name: Install latest version of Google Chrome using APT
  include_tasks: setup-apt.yml
  when: ansible_pkg_mgr == 'apt'

- name: Install latest version of Google Chrome using DNF
  include_tasks: setup-dnf.yml
  when: ansible_pkg_mgr == 'dnf'

- name: Install latest version of Google Chrome using YUM
  include_tasks: setup-yum.yml
  when: ansible_pkg_mgr == 'yum'
