# dnf tasks file for ansible-role-chrome


- name: Add Google Chrome repository
  yum_repository:
    name: google-chrome
    description: "Google Chrome Stable repository"
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub
    gpgcheck: yes

- name: "dnf | ensure Google chrome present"
  dnf:
    name: google-chrome-stable
    state: latest

