---
pip3_package_name: python3-pip
python3_package_name: python3
python3_devtools_package_name: python3-dev
python3_setuptools_package_name: python3-setuptools
python_virtualenv_package_name: python3-virtualenv
ipython_package_name: ipython3
pylint_package_name: pylint
