---
- name: Add Vivaldi repository
  yum_repository:
    name: vivaldi
    description: "Vivaldi"
    baseurl: https://repo.vivaldi.com/archive/rpm/$basearch
    gpgkey: https://repo.vivaldi.com/archive/linux_signing_key.pub
    gpgcheck: true
    enabled: true

- name: "dnf | ensure Vivaldi present"
  dnf:
    name: vivaldi-stable
    state: latest
