---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"
  when: (mariadb_version is not defined)

- name: Add MariaDB repository
  yum_repository:
    name: mariadb
    description: "MariaDB repository"
    baseurl: http://yum.mariadb.org/{{ mariadb_version }}/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes

- name: "yum | install MariaDB client"
  yum:
    name: mariadb
    state: latest

- name: "yum | install MariaDB server"
  yum:
    name: mariadb-server
    state: latest

