---
- name: include mariadb variables
  include_vars:
    file: ../vars/mariadb.yml

- name: Add MariaDB repository
  yum_repository:
    name: mariadb
    description: "MariaDB repository"
    baseurl: http://yum.mariadb.org/{{ mariadb_version }}/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes

- name: "yum | install MariaDB client"
  yum:
    name: mariadb
    state: latest

- name: "yum | install MariaDB server"
  yum:
    name: mariadb-server
    state: latest

