---
- name: include mariadb variables
  include_vars:
    file: ../vars/mariadb.yml

- name: "apt | ensure MariaDB signing keys present"
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{item}}"
  with_items:
    - cbcb082a1bb943db
    - F1656F24C74CD1D8

- name: "apt | ensure MariaDB repo present"
  copy:
    content: "deb [arch=amd64] http://ftp.osuosl.org/pub/mariadb/repo/{{ mariadb_version }}/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} main"
    dest: "/etc/apt/sources.list.d/mariadb.list"

- name: "apt | ensure MariaDB client and server installed"
  apt:
    name: "{{item}}"
    update_cache: yes
    state: latest
  with_items:
    - mariadb-server
    - mariadb-client

- name: Determine required MySQL Python libraries.
  set_fact:
    deb_mysql_python_package: "{% if 'python3' in ansible_python_interpreter|default('') %}python3-mysqldb{% else %}python-mysqldb{% endif %}"

- name: Ensure MySQL Python libraries are installed.
  apt: "name={{ deb_mysql_python_package }} state=present"
