---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"
      skip: true
  when: (pip3_package_name is not defined) or (python3_devtools_package_name is not defined) or (python3_package_name is not defined) or (python3_setuptools_package_name is not defined) or (python_virtualenv_package_name is not defined) or (ipython_package_name is not defined)

- name: install the latest version of python3
  package:
    name: "{{ python3_package_name }}"
    state: latest

- name: install the latest version of pip3
  package:
    name: "{{ pip3_package_name }}"
    state: latest

- name: install the latest version of python3 development tools
  package:
    name: "{{ python3_devtools_package_name }}"
    state: latest

- name: install the latest version of python3 setuptools
  package:
    name: "{{ python3_setuptools_package_name }}"
    state: latest

- name: install the latest version of python virtualenv
  package:
    name: "{{ python_virtualenv_package_name }}"
    state: latest

- name: install the latest version of ipython
  package:
    name: "{{ ipython_package_name }}"
    state: latest

- include: "pycharm.yml"
  tags: gui
