---
# https://wiki.debian.org/JetBrains

- name: "apt | ensure JetBrains signing key present"
  shell: wget -O- https://s3.eu-central-1.amazonaws.com/jetbrains-ppa/0xA6E8698A.pub.asc | gpg --dearmor > /etc/apt/keyrings/jetbrains.gpg

- name: "apt | ensure JetBrains repo present"
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/jetbrains.gpg] https://jetbrains-ppa.s3-website.eu-central-1.amazonaws.com {{ ansible_distribution_release }} main"
    state: present
    update_cache: true

- name: "apt | ensure JetBrains PyCharm Community latest instaled"
  apt:
    name: pycharm-community
    state: latest
