---
- name: "flatpak | force repair"
  shell: "/usr/bin/flatpak repair"

- name: "flatpak | install latest version of Pycharm"
  flatpak:
    name: com.jetbrains.PyCharm-Community
    state: present
    remote: flathub
  register: install_pycharm
  until: install_pycharm is not failed
  retries: 5
