---
- name: Add linux-surface repository.
  get_url:
    url: https://pkg.surfacelinux.com/fedora/linux-surface.repo
    dest: '/etc/yum.repos.d/linux-surface.repo'
    owner: root
    group: root
    mode: 0644

- name: Install kernel and firmware
  package:
    name: kernel-surface
    state: latest

- name: Install touchscreen daemon
  package:
    name: iptsd
    state: latest

- name: Install wacom surface library
  #dnf:
  #  name: libwacom-surface
  #  allowerasing: true
  #  state: latest
  #
  #  temporarily use shell module since Ansible 2.9 doesn't support dnf module allowerasing option
  shell: "dnf install -y --allowerasing libwacom-surface"
  when: ansible_pkg_mgr == 'dnf'

- name: Install secureboot key
  dnf:
    name: surface-secureboot
    state: latest
  register: secureboot
  when: ansible_pkg_mgr == 'dnf'

- name: Print secureboot information
  debug:
    msg: "secureboot info: {{ secureboot }}"
    verbosity: 0
  when: secureboot is defined
