---
- name: Determine Homebrew ownership variables
  set_fact:
    homebrew_user: '{{ homebrew_user | default(ansible_user_id) }}'
    homebrew_group: '{{ homebrew_group | default(ansible_user_gid) }}'

- name: import personal-related defaults
  include_vars:
    file: ../defaults/personal.yml

- block:
  # taps personal
  - name: Ensure configured personal taps are tapped.
    homebrew_tap:
      tap: '{{ item.name | default(item) }}'
      url: '{{ item.url | default(omit) }}'
      state: present
    loop: "{{ homebrew_taps_personal }}"
    become_user: "{{ homebrew_user }}"
    ignore_errors: true

  # Cask personal.
  - name: Install configured personal-related cask applications.
    homebrew_cask:
      name: "{{ item.name | default(item) }}"
      state: present
      install_options: "{{ item.install_options | default('appdir=' + homebrew_cask_appdir) }}"
      accept_external_apps: "{{ homebrew_cask_accept_external_apps }}"
    loop: "{{ homebrew_cask_apps_personal }}"
    become_user: "{{ homebrew_user }}"
    ignore_errors: true

  # Brew.
  - name: Ensure configured personal-related homebrew packages are installed.
    homebrew:
      name: "{{ item.name | default(item) }}"
      install_options: "{{ item.install_options | default(omit) }}"
      state: present
    loop: "{{ homebrew_installed_packages_personal }}"
    become_user: "{{ homebrew_user }}"
    ignore_errors: true
