---
- name: Install homebrew
  include_tasks: homebrew.yml

- name: enable startup chime
  # https://mrmacintosh.com/how-to-enable-the-mac-startup-chime-on-your-2016-macbook-pro/
  shell: nvram StartupMute=%00
