---
- name: disable NetworkManager
  include: networking.yml
  when: BasePlaybook != "laptop.yml" and BasePlaybook != "tablet.yml"

- name: install latest version of ethtool package
  package:
    name: ethtool
    state: latest

- name: include libvirt and KVM
  include: libvirt.yml

- name: include kcli tool
  include: kcli.yml
