---
# comment out for now until ready for it
#- name: disable NetworkManager
#  include_tasks: networking.yml
#  when: base_playbook != "laptop.yml" and base_playbook != "tablet.yml"

- name: install latest version of ethtool package
  package:
    name: ethtool
    state: latest

- name: include libvirt and KVM
  include_tasks: libvirt.yml

- name: include kcli tool
  include_tasks: kcli.yml
