---
- name: make backup of current /etc/resolv.conf and store temporarily
  copy:
    src: /etc/resolv.conf
    dest: /tmp/resolv.conf
    remote_src: true
    follow: true

- name: Populate service facts
  service_facts:

- name: stop and disable NetworkManager service
  systemd:
    name: NetworkManager
    state: stopped
    enabled: false
  when: "'NetworkManager.service' in services"

- name: unlink NetworkManager-created /etc/resolv.conf
  file:
    path: /etc/resolv.conf
    state: absent

- name: restore /etc/resolv.conf
  copy:
    src: /tmp/resolv.conf
    dest: /etc/resolv.conf
    remote_src: true
