---
- name: include main non-free apt source as pre-requisite for unrar on Debian systems
  include: non-free-debian.yml
  when: ansible_distribution == 'Debian'

- name: Install VIM
  include: vim.yml

- name: Install and configure SSH
  include: ssh.yml

- name: Install tools and utilities
  include: tools.yml

- name: Install and configure GPG
  include: gpg.yml

- name: Install and configure tmux
  include: tmux.yml

- name: Install latest version of Neofetch on Debian
  include: neofetch-debian.yml
  when: ansible_distribution == 'Debian'

- name: Install latest version of Neofetch on Ubuntu
  include: neofetch-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Install latest version of Neofetch using YUM
  include: neofetch-yum.yml
  when: ansible_pkg_mgr == 'yum'
