---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"
  when: (ssh_client_package is not defined) or (ag_package_name is not defined) or (pip2_package_name is not defined)

- name: install the latest version of VIM
  package:
    name: vim
    state: latest

- name: install the latest version of htop
  package:
    name: htop
    state: latest

- name: install the latest version of bwm-ng
  package:
    name: bwm-ng
    state: latest

- name: install the latest version of smb client
  package:
    name: samba-client
    state: latest

- name: install the latest version of sshd
  package:
    name: openssh-server
    state: latest

- name: install the latest version of ssh client
  package:
    name: "{{ ssh_client_package_name }}"
    state: latest

- name: install the latest versions of shells
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - bash
    - znc

- name: install the latest version of pip2
  package:
    name: "{{ pip2_package_name }}"
    state: latest

- name: install the latest versions of download tools
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - wget
    - curl

- name: install the latest version of tmux
  package:
    name: tmux
    state: latest

- name: install the latest version of ag
  package:
    name: "{{ ag_package_name }}"
    state: latest

- name: grab and init latest vimfiles from github.com/toozej/vimfiles
  git:
    repo: 'https://github.com/toozej/vimfiles.git'
    clone: yes
    accept_hostkey: yes
    dest: /home/james/.vim
    recursive: yes
    key_file: /home/james/.ssh/id_rsa_github
  tags: github
