---
- name: Install EPEL repo on RHEL-based systems
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
  when: (ansible_distribution == 'Red Hat Enterprise Linux') or (ansible_distribution == 'CentOS')

- name: Import EPEL GPG key on RHEL-based systems
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
    state: present
  when: (ansible_distribution == 'Red Hat Enterprise Linux') or (ansible_distribution == 'CentOS')

- name: install the latest version of libselinux-python package on RedHat-based systems
  package:
    name: libselinux-python
    state: latest
  when: ansible_os_family == 'RedHat'

- name: include RPMFusion repo as pre-requisite for unrar on RedHat-based systems
  include_role:
    name: repo-extra
  when: ansible_os_family == 'RedHat'
  
- name: include main non-free apt source as pre-requisite for unrar on Debian systems
  include: non-free-debian.yml
  when: ansible_distribution == 'Debian'

- name: Install VIM and vimfiles
  include: vim.yml

- name: Install and configure SSH
  include: ssh.yml

- name: Install tools and utilities
  include: tools.yml

- name: Install and configure GPG
  include: gpg.yml

- name: Install and configure tmux
  include: tmux.yml

- name: Install latest version of ripgrep on Debian-based
  include: ripgrep-debian.yml
  when: ansible_os_family == 'Debian'

- name: Install latest version of ripgrep using YUM
  include: ripgrep-yum.yml
  when: ansible_pkg_mgr == 'yum'

- name: Install latest version of ripgrep using DNF
  package:
    name: ripgrep
    state: latest
  when: ansible_pkg_mgr == 'dnf'

- name: Install latest version of Neofetch on Debian
  include: neofetch-debian.yml
  when: ansible_distribution == 'Debian'

- name: Install latest version of Neofetch on Ubuntu
  include: neofetch-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Install latest version of Neofetch using YUM
  include: neofetch-yum.yml
  when: ansible_pkg_mgr == 'yum'

- name: Install latest version of Neofetch using DNF
  include: neofetch-dnf.yml
  when: ansible_pkg_mgr == 'dnf'
