---
- name: "apt | ensure BinTray signing keys present"
  raw: curl -L "https://bintray.com/user/downloadSubjectPublicKey?username=bintray" -o Release-neofetch.key && apt-key add Release-neofetch.key && rm Release-neofetch.key

- name: "apt | ensure BinTray repo present"
  apt_repository:
    repo: "deb http://dl.bintray.com/dawidd6/neofetch stable main"
    state: present
    filename: neofetch.list

- name: "apt | ensure neofetch installed"
  apt:
    name: neofetch
    update_cache: yes
    state: latest
