---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"

- name: "apt | enable non-free main repo for Debian"
  apt_repository:
    repo: deb http://debian.osuosl.org/debian/ {{ ansible_distribution_release }} main non-free
    state: present
