---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"
      skip: True
  when: (ripgrep_release is not defined)

- name: "apt | download ripgrep deb package"
  get_url:
    url: https://github.com/BurntSushi/ripgrep/releases/download/{{ ripgrep_release }}/ripgrep_{{ ripgrep_release }}_amd64.deb
    dest: /tmp/ripgrep.deb

- name: "apt | ensure ripgrep installed"
  apt:
    deb: /tmp/ripgrep.deb
