---
- name: "yum | Add ripgrep repository"
  get_url:
    url: https://copr.fedorainfracloud.org/coprs/carlwgeorge/ripgrep/repo/epel-{{ ansible_distribution_major_version|int }}/carlwgeorge-ripgrep-epel-{{ ansible_distribution_major_version|int }}.repo
    dest: /etc/yum.repos.d/copr_carlwgeorge_ripgrep.repo

- name: "yum | ensure ripgrep present"
  yum:
    name: ripgrep
    state: latest
