---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}-{{ ansible_distribution_major_version | int }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"
      skip: true
  when: (ssh_client_package_name is not defined) or (ssh_daemon_package_name is not defined) or (sshd_service_name is not defined)

- name: install the latest version of sshd
  package:
    name: "{{ ssh_daemon_package_name }}"
    state: latest

- name: install the latest version of ssh client
  package:
    name: "{{ ssh_client_package_name }}"
    state: latest

- name: Disallow root SSH access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: Restart ssh

- name: Disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: Restart ssh

- name: Disallow agent forwarding
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^AllowAgentForwarding"
    line: "AllowAgentForwarding no"
    state: present
  notify: Restart ssh

- name: set allowed algorithms, ciphers and MACs in ssh client config
  blockinfile:
    path: /etc/ssh/ssh_config
    insertafter: EOF
    state: present
    content: |
      HostKeyAlgorithms ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,rsa-sha2-256,rsa-sha2-256-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-512-cert-v01@openssh.com
      Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
      KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256
      MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com
    backup: true
  notify: Restart ssh

- name: set allowed algorithms, ciphers and MACs in sshd config
  blockinfile:
    path: /etc/ssh/sshd_config
    insertafter: EOF
    state: present
    content: |
      KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256
      HostKeyAlgorithms rsa-sha2-512,rsa-sha2-256,ssh-ed25519
      Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
      MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com
    backup: true
  notify: Restart ssh
