---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}-{{ ansible_distribution_major_version | int }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"
      skip: True
  when: (ag_package_name is not defined) or (pip3_package_name is not defined) or (p7zip_package_name is not defined)

- name: install the latest versions of system monitoring utilities
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - htop
    - iotop
    - powertop
    - ncdu
    - lshw
    - net-tools

- name: install bwm-ng except on CentOS
  package:
    name: bwm-ng
    state: latest
  when: ansible_distribution != 'CentOS'

- name: install the latest version of Samba client and tools
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - samba-client
    - cifs-utils

- name: install the latest version of pip3
  package:
    name: "{{ pip3_package_name }}"
    state: latest

- name: install the latest versions of download tools
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - wget
    - curl

- name: install the latest version of archiving tools
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - zip
    - "{{ p7zip_package_name }}"
    - pigz

- name: install the latest version of unrar except on CentOS
  package:
    name: unrar
    state: latest
  when: ansible_distribution != 'CentOS'

- name: install the latest version of tree
  package:
    name: tree
    state: latest

- name: install the latest version of ag
  package:
    name: "{{ ag_package_name }}"
    state: latest

- name: install the latest version of strace
  package:
    name: strace
    state: latest
