---
- name: install the latest version of VIM
  package:
    name: vim
    state: latest

# yamllint package required by ALE vim plugin
- name: install the latest version of yamllint
  package:
    name: yamllint
    state: latest
