---

galaxy_info:
  author: groks
  description: yum repositories for rpmfusion-free, rpmfusion-nonfree, livna
  license: BSD
  min_ansible_version: 1.3

  platforms:
  - name: Fedora
    versions:
    - all

  categories:
  - packaging

dependencies: []
