---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"
      skip: true

- name: ensure docker-compose v1 no longer installed
  file:
    state: absent
    path: /usr/local/bin/docker-compose

- name: install docker compose v2
  package:
    name: docker-compose-plugin
    state: latest
