---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: latest
  notify: restart docker

# TODO: Remove this shim once 18.09.1 or later is released.
- import_tasks: docker-1809-shim.yml
  when: ansible_service_mgr == "systemd"

# docker-py from https://github.com/docker/docker-py renamed to docker on PyPi https://pypi.org/project/docker/
- name: Install docker-py lib
  pip:
    name: docker
    state: latest

# Docker must be stopped to work Docker in Docker (testing with Jenkins)
- name: Ensure Docker is stopped and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"
  when: (ansible_service_mgr == "systemd") or (ansible_service_mgr == "upstart")

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: docker-compose.yml
  when: docker_install_compose

- include_tasks: docker-users.yml
  when: docker_users
