---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: latest
  notify: restart docker

# docker-py from https://github.com/docker/docker-py renamed to docker on PyPi https://pypi.org/project/docker/
- name: ensure deprecated docker-py lib is absent
  pip:
    name: docker-py
    state: absent

- name: Install latest docker-py lib
  pip:
    name: docker
    state: latest

- name: Install docker python library
  package:
    name: python-docker
    state: present
  when: ansible_distribution_release == "buster" or ansible_distribution_release == "bullseye"

# Docker must be stopped to work Docker in Docker (testing with Jenkins)
- name: Ensure Docker is stopped and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"
  when: (ansible_service_mgr == "systemd") or (ansible_service_mgr == "upstart")

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: docker-compose.yml
  when: docker_install_compose

- include_tasks: docker-users.yml
