---
- name: ensure Grubby utility is installed
  package:
    name: grubby
    state: latest

- name: disable cgroups v2
  shell: grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"

# https://pastebin.com/Zq3Gev7w
- name: switch firewalld to iptables to support Docker
  shell: sed -i 's/FirewallBackend=nftables/FirewallBackend=iptables/g' /etc/firewalld/firewalld.conf
  notify: restart firewalld

# https://github.com/docker/for-linux/issues/955#issuecomment-620932240
- name: add Docker interface to trusted firewall zone
  shell: |
    firewall-cmd --permanent --zone=trusted --add-interface=docker0
    firewall-cmd --reload
