---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"
      skip: True
  when: (dev_tools_package_name is not defined) or (nss_tools_package_name is not defined)

- name: install the latest version of Development Tools
  package:
    name: "{{ dev_tools_package_name }}"
    state: latest

- name: install the latest version of certutil
  package:
    name: "{{ nss_tools_package_name }}"
    state: latest

- name: include wuzz defaults
  include_vars:
    file: ../defaults/wuzz.yml

- name: install the latest version of Wuzz
  get_url:
    url:  https://github.com/asciimoo/wuzz/releases/download/v{{ wuzz_version }}/wuzz_linux_amd64
    dest: /usr/local/bin/wuzz
    force: yes

- name: install latest version of Github's hub tool
  include: hub.yml
