---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"
      skip: true
  when: (dev_tools_package_name is not defined) or (nss_tools_package_name is not defined) or (shellcheck_package_name is not defined)

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: install the latest version of Development Tools
  package:
    name: "{{ dev_tools_package_name }}"
    state: latest

- name: install the latest version of certutil
  package:
    name: "{{ nss_tools_package_name }}"
    state: latest

- name: install the latest version of openssl tools
  package:
    name: openssl
    state: latest

- name: install the latest version of pre-commit
  package:
    name: pre-commit
    state: latest
  when: ansible_distribution != 'Ubuntu'

- name: install the latest version of shellcheck
  package:
    name: "{{ shellcheck_package_name }}"
    state: latest

- include_tasks: wuzz.yml

- name: include Tea defaults
  include_vars:
    file: ../defaults/tea.yml

- name: install the latest version of Tea (Gitea client)
  get_url:
    url: https://dl.gitea.io/tea/{{ tea_version }}/tea-{{ tea_version }}-linux-amd64
    dest: /usr/local/bin/tea
    force: true

- name: set Tea as executable
  file:
    path: /usr/local/bin/tea
    owner: root
    group: root
    mode: 0755
