---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"
  when: (dev_tools_package is not defined)

- name: install the latest version of Development Tools
  package:
    name: "{{ dev_tools_package_name }}"
    state: latest

- name: install the latest versions of Git tools
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - git-review
    - git-flow

- name: Install latest version of DBeaver using APT
  include: dbeaver-apt.yml
  when: ansible_pkg_mgr == 'apt'

- name: Install latest version of DBeaver using DNF
  include: dbeaver-dnf.yml
  when: ansible_pkg_mgr == 'dnf'

- name: Install latest version of DBeaver using YUM
  include: dbeaver-yum.yml
  when: ansible_pkg_mgr == 'yum'
