---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"
      skip: true
  when: (dev_tools_package_name is not defined) or (nss_tools_package_name is not defined)

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: install the latest version of Development Tools
  package:
    name: "{{ dev_tools_package_name }}"
    state: latest

- name: install the latest version of certutil
  package:
    name: "{{ nss_tools_package_name }}"
    state: latest

# pre-commit package not yet available in Ubuntu and Debian default repos
- name: install the latest version of pre-commit
  package:
    name: pre-commit
    state: latest
  when: ansible_distribution == 'Fedora'

- name: include wuzz defaults
  include_vars:
    file: ../defaults/wuzz.yml

- name: install the latest version of Wuzz
  get_url:
    url:  https://github.com/asciimoo/wuzz/releases/download/v{{ wuzz_version }}/wuzz_linux_amd64
    dest: /usr/local/bin/wuzz
    force: yes
