---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"
      skip: true
  when: (cron_package_name is not defined)

- name: install cron daemon
  package:
    name: "{{ cron_package_name }}"
    state: latest

- name: setup cron job for pulling registered repos
  ansible.builtin.cron:
    name: "Update registered repos with mr"
    user: james
    minute: "0"
    hour: "12"
    job: "mr -j 5 update > /dev/null"
