- name: Add Github Hub apt key.
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 23F3D4EA75716059

- name: Add Github CLI repository.
  apt_repository:
    repo: "deb https://cli.github.com/packages stable main"
    state: present
    update_cache: true

- name: install the latest verion of Github CLI
  package:
    name: gh
    state: latest
