---
- name: Add Github Hub apt key.
  get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /usr/share/keyrings/githubcli-archive-keyring.gpg
    mode: '0644'

- name: Add Github CLI repository.
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
    state: present
    update_cache: true

- name: install the latest verion of Github CLI
  package:
    name: gh
    state: latest
