- name: Add Github Hub apt key.
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: C99B11DEB97541F0

- name: Add Github CLI repository.
  apt_repository:
    repo: "deb https://cli.github.com/packages focal main"
    state: present
    update_cache: true

- name: install the latest verion of Github CLI
  package:
    name: gh
    state: latest
