---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"
      skip: true

- name: install latest Wuzz from GitHub releases
  import_role:
    name: github-releases
  vars:
    org: asciimoo
    repo: wuzz
    filename: wuzz
    instpath: /usr/local/bin/
    arch: amd64
    version: latest
    project_url: https://api.github.com/repos/{{ org }}/{{ repo }}/releases
  tags: gh-releases
