---
# handlers file for monitoring
- name: stop netdata service
  service:
    name: netdata
    state: stopped
  when: netdata_present.stat.exists == True

- name: start and enable netdata systemd
  systemd:
    name: netdata
    state: started
    enabled: yes
    daemon_reload: yes
  become: true

- name: start and enable netdata service
  service:
    name: netdata
    state: started
    enabled: yes
  become: true

- name: start and enable zabbix-agent service
  service:
    name: zabbix-agent
    state: started
    enabled: yes
  become: true
