---
# execute this playbook `sudo ANSIBLE_ROLES_PATH=/home/james/src/github/toozej/ansible/roles ansible-playbook playbooks/go-only.yml`
- name: audio-only
  hosts: all
  tasks:
    - name: audio-cli
      include_role:
        name: audio-cli
    - name: audio-gui
      include_role:
        name: audio-gui
