---
# Playbook to setup a common environment for system bootstrapping
- name: Setup common environment
  hosts: all
  become: true
  become_user: root
  roles:
    - role: james
    - role: repo-extra
    - role: common
    - role: unattended-upgrades
