---
# Playbook to setup a desktop system with full toolchain
- import_playbook: common.yml
- import_playbook: virt-server.yml
- import_playbook: gnome.yml

- name: Setup desktop environment
  hosts: all
  become: true
  become_user: root
  roles:
    - role: flatpak

- name: Setup programs and tools
  hosts: all
  become: true
  become_user: root
  roles:
    - role: chrome
    - role: audio-cli
    - role: audio-gui
    - role: office
    - role: photography
    - role: wine
    - role: gaming
