---
# Playbook to setup a desktop system with full toolchain
- hosts: all
  pre_tasks:
    - name: Set BasePlaybook Fact
      set_fact:
        BasePlaybook: "{{ (lookup('file', '/proc/self/cmdline') | regex_replace('\u0000',' ')).split()|select('match','^[a-z-_/]*[.]y[a]*ml')|list|first|basename }}"
      when: BasePlaybook is not defined

- import_playbook: common.yml
- import_playbook: file-server.yml
- import_playbook: virt-server.yml
- import_playbook: gnome.yml

- name: Setup desktop environment
  hosts: all
  become: true
  become_user: root
  roles:
    - role: flatpak

- name: Setup programs and tools
  hosts: all
  become: true
  become_user: root
  roles:
    - role: chrome
    - role: audio-cli
    - role: audio-gui
    - role: dev-gui
    - role: office
    - role: photography
    - role: wine
    - role: gaming
