---
# Playbook to setup a development environment
- hosts: all
  pre_tasks:
    - name: Set base_playbook Fact
      set_fact:
        base_playbook: "{{ (lookup('file', '/proc/self/cmdline') | regex_replace('\u0000',' ')).split()|select('match','^[a-z-_/]*[.]y[a]*ml')|list|first|basename }}"
      when: base_playbook is not defined


- import_playbook: common.yml
- import_playbook: virt-server.yml
- import_playbook: docker-server.yml

- name: Setup dev environment
  hosts: all
  become: true
  become_user: root
  roles:
    - role: dev-common
    - role: java
    - role: dev-aws
    - role: dev-ansible
    - role: dev-go
    - role: dev-kubernetes
    - role: dev-python
    - role: dev-ruby
    - role: dev-terraform
