---
# Playbook to setup a development environment
- name: Setup common environment
  hosts: all
  become: true
  become_user: root
  roles:
    - role: ansible-enablement
    - role: user
    - role: common
    - role: dev-common

- name: Setup Docker environment
  hosts: all
  become: true
  become_user: root
  roles:
    - role: docker

- name: Setup dev environment
  hosts: all
  become: true
  become_user: root
  roles:
    - role: dev-ansible
    - role: dev-go
    - role: dev-kubernetes
    - role: dev-python
    - role: dev-ruby
