---
# Playbook to setup a Docker host
- name: Setup Docker environment
  hosts: all
  become: true
  become_user: root
  roles:
    - role: docker

- name: Setup server monitoring via Netdata
  hosts: all
  become: true
  become_user: root
  roles:
    - role: monitoring
