---
# Playbook to setup a basic fileserver
- name: Setup file server
  hosts: all
  become: true
  become_user: root
  roles:
    - role: file-server

- name: Setup server monitoring via Netdata
  hosts: all
  become: true
  become_user: root
  roles:
    - role: monitoring
