---
- hosts: all
  pre_tasks:
    - name: Set base_playbook Fact
      set_fact:
        base_playbook: "{{ (lookup('file', '/proc/self/cmdline') | regex_replace('\u0000',' ')).split()|select('match','^[a-z-_/]*[.]y[a]*ml')|list|first|basename }}"
      when: base_playbook is not defined

- name: Setup Gnome Desktop environment
  hosts: all
  become: true
  become_user: root
  roles:
    - role: flatpak
    - role: gui-common
    - role: gui-gnome
