---
# Playbook to setup a laptop system
- name: Setup common environment
  hosts: all
  become: true
  become_user: root
  roles:
    - role: repo-extra
    - role: common

- name: Setup laptop-specific fixes
  hosts: all
  become: true
  become_user: root
  roles:
    - role: hp-spectre-13

- name: Setup Docker environment
  hosts: all
  become: true
  become_user: root
  roles:
    - role: docker

- name: Setup GUI
  hosts: all
  become: true
  become_user: root
  roles:
    - role: gui-common
    - role: gui-gnome

- name: Setup programs and tools
  hosts: all
  become: true
  become_user: root
  roles:
    - role: chrome
    - role: audio-cli
    - role: audio-gui
    - role: office
    - role: openvpn-client

- name: Setup minimal dev environment
  hosts: all
  become: true
  become_user: root
  roles:
    - role: dev-ansible
    - role: dev-python
    - role: vagrant
