---
# Playbook to setup a laptop system
- hosts: all
  pre_tasks:
    - name: Set base_playbook Fact
      set_fact:
        base_playbook: "{{ (lookup('file', '/proc/self/cmdline') | regex_replace('\u0000',' ')).split()|select('match','^[a-z-_/]*[.]y[a]*ml')|list|first|basename }}"
      when: base_playbook is not defined

# Run with sudo and `--skip-tags=personal` for work, or `--skip-tags=work` for personal
- name: Setup Mac software
  hosts: localhost
  become: true
  roles:
    - role: mac
      tags:
        - personal
