---
# Playbook to setup a mac
#
# Run with sudo and `--skip-tags=personal` for work, or `--skip-tags=work` for personal
- name: Setup Mac software
  hosts: localhost
  become: true
  roles:
    - role: mac
      tags:
        - work
        - personal
