---
# Playbook to setup a mac
- name: Setup common environment
  hosts: all
  become: true
  become_user: root
  roles:
    - role: user

- name: Setup Mac software
  hosts: all
  become: true
  become_user: root
  roles:
    - role: mac
