---
# Playbook to setup a media server
- name: Setup common environment
  hosts: all
  become: true
  become_user: root
  roles:
    - role: ansible-enablement
    - role: user
    - role: common

- name: Setup file server
  hosts: all
  become: true
  become_user: root
  roles:
    - role: file-server

- name: Setup Docker environment
  hosts: all
  become: true
  become_user: root
  roles:
    - role: docker

- name: Setup server monitoring via Netdata
  hosts: all
  become: true
  become_user: root
  roles:
    - role: monitoring

- name: Setup Backup and Restore tools
  hosts: all
  become: true
  become_user: root
  roles:
    - role: backup-restore
