---
# Playbook to setup a multi-purpose server
- hosts: all
  pre_tasks:
    - name: Set BasePlaybook Fact
      set_fact:
        BasePlaybook: "{{ (lookup('file', '/proc/self/cmdline') | regex_replace('\u0000',' ')).split()|select('match','^[a-z-_/]*[.]y[a]*ml')|list|first|basename }}"
      when: BasePlaybook is not defined

- name: Setup common environment
  hosts: all
  become: true
  become_user: root
  roles:
    - role: ansible-enablement
    - role: user
    - role: common
    - role: unattended-upgrades
    - role: hardening

- name: Setup file server
  hosts: all
  become: true
  become_user: root
  roles:
    - role: fs-common
    - role: file-server

- name: Setup Docker environment
  hosts: all
  become: true
  become_user: root
  roles:
    - role: docker

- name: Setup virt server
  hosts: all
  become: true
  become_user: root
  roles:
    - role: virt-server
