---
# Playbook to setup a multi-purpose server
- hosts: all
  pre_tasks:
    - name: Set base_playbook Fact
      set_fact:
        base_playbook: "{{ (lookup('file', '/proc/self/cmdline') | regex_replace('\u0000',' ')).split()|select('match','^[a-z-_/]*[.]y[a]*ml')|list|first|basename }}"
      when: base_playbook is not defined

- import_playbook: common.yml
- import_playbook: file-server.yml
- import_playbook: docker-server.yml
- import_playbook: virt-server.yml

# disable until ready for it
#- name: Setup hardening
#  hosts: all
#  become: true
#  become_user: root
#  roles:
#    - role: hardening
