---
# execute this playbook `sudo ANSIBLE_ROLES_PATH=/home/james/src/github/toozej/ansible/roles ansible-playbook playbooks/simplenote-only.yml`
- name: simplenote-only
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Simplenote only
      include_role:
        name: gui-common
        tasks_from: simplenote
