---
# execute this playbook `sudo ANSIBLE_ROLES_PATH=/home/james/src/github/toozej/ansible/roles ansible-playbook playbooks/update-github-releases-only.yml --tags "gh-releases"`
- hosts: localhost
  connection: local
  become: true
  roles:
    #- {role: ../roles/docker}
    - {role: ../roles/gui-common}
    #- {role: ../roles/dev-common}
  tags:
    - gh-releases
