---
# Playbook to setup a KVM-QEMU virtualization host
- name: Setup Docker environment
  hosts: all
  become: true
  become_user: root
  roles:
    - role: docker

- name: Setup virt server
  hosts: all
  become: true
  become_user: root
  roles:
    - role: virt-server
