---
- name: Install latest version of RPMFusion using DNF
  include_tasks: setup-dnf.yml
  when: ansible_pkg_mgr == 'dnf'

- name: Install latest version of RPMFusion using YUM
  include_tasks: setup-yum.yml
  when: ansible_pkg_mgr == 'yum'
