---
- name: upload rpmfusion repo GPG keys for Fedora
  copy:
    src: "files/{{ item }}"
    dest: "/tmp/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - "RPM-GPG-KEY-rpmfusion-free-fedora-32"
    - "RPM-GPG-KEY-rpmfusion-nonfree-fedora-32"

- name: import rpmfusion repo GPG keys for Fedora
  rpm_key:
    state: present
    key: "{{ item }}"
  with_items:
    - "/tmp/RPM-GPG-KEY-rpmfusion-free-fedora-32"
    - "/tmp/RPM-GPG-KEY-rpmfusion-nonfree-fedora-32"
  when: ansible_distribution == 'Fedora'

- name: install rpmfusion repo using dnf for Fedora
  dnf:
    name: ['https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm', 'https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm']
    state: present
    enablerepo: True
    update_cache: True
  when: ansible_distribution == 'Fedora'

- name: upload rpmfusion repo GPG keys for RedHat
  copy:
    src: "files/{{ item }}"
    dest: "/tmp/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - "RPM-GPG-KEY-rpmfusion-free-el-8"
    - "RPM-GPG-KEY-rpmfusion-nonfree-el-8"

- name: import rpmfusion repo GPG keys for RedHat
  rpm_key:
    state: present
    key: "{{ item }}"
  with_items:
    - "/tmp/RPM-GPG-KEY-rpmfusion-free-el-8"
    - "/tmp/RPM-GPG-KEY-rpmfusion-nonfree-el-8"
  when: (ansible_distribution == 'RedHat') or (ansible_distribution == 'CentOS')

- name: install rpmfusion repo using dnf for RedHat
  dnf:
    name: ['https://download1.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_distribution_major_version|int }}.noarch.rpm','https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_distribution_major_version|int }}.noarch.rpm']
    state: present
    enablerepo: True
    update_cache: True
  when: (ansible_distribution == 'RedHat') or (ansible_distribution == 'CentOS')
