---
- name: install rpmfusion repo using dnf for Fedora
  dnf:
    name: ['https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm', 'https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm']
    state: present
    enablerepo: True
    update_cache: True
  when: ansible_distribution == 'Fedora'

- name: install rpmfusion repo using dnf for RedHat
  dnf:
    name: ['https://download1.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_distribution_major_version|int }}.noarch.rpm','https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_distribution_major_version|int }}.noarch.rpm']
    state: present
    enablerepo: True
    update_cache: True
  when: (ansible_distribution == 'RedHat') or (ansible_distribution == 'CentOS')
