---
- name: import rpmfusion repo GPG keys for RedHat
  rpm_key:
    state: present
    key: "{{ item }}"
  with_items:
    - "837935CD19E123AA7F8A8E69979F0C69158B3811"
    - "CF9FD59F61D6612146CDAC8E14B6792DBDDA8475"
  when: (ansible_distribution == 'RedHat') or (ansible_distribution == 'CentOS')

- name: install rpmfusion yum repo for RedHat
  yum:
    name: ['http://download1.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_distribution_major_version|int }}.noarch.rpm', 'http://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_distribution_major_version|int }}.noarch.rpm']
    state: present
    enablerepo: True
    update_cache: True
  when: (ansible_distribution == 'RedHat') or (ansible_distribution == 'CentOS')
