---
- name: upload rpmfusion repo GPG keys for RedHat
  copy:
    src: "files/{{ item }}"
    dest: "/tmp/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - "RPM-GPG-KEY-rpmfusion-free-el-8"
    - "RPM-GPG-KEY-rpmfusion-nonfree-el-8"

- name: import rpmfusion repo GPG keys for RedHat
  rpm_key:
    state: present
    key: "{{ item }}"
  with_items:
    - "/tmp/RPM-GPG-KEY-rpmfusion-free-el-8"
    - "/tmp/RPM-GPG-KEY-rpmfusion-nonfree-el-8"
  when: (ansible_distribution == 'RedHat') or (ansible_distribution == 'CentOS')

- name: install rpmfusion yum repo for RedHat
  yum:
    name: ['http://download1.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_distribution_major_version|int }}.noarch.rpm', 'http://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_distribution_major_version|int }}.noarch.rpm']
    state: present
    enablerepo: True
    update_cache: True
  when: (ansible_distribution == 'RedHat') or (ansible_distribution == 'CentOS')
