---
- name: download rpmfusion repo GPG keys for Fedora
  get_url:
    url: "{{ item }}"
    dest: "/tmp/"
    force: true
    owner: root
    group: root
    mode: 0644
  with_items:
    - "https://rpmfusion.org/keys?action=AttachFile&do=view&target=RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_distribution_version }}"
    - "https://rpmfusion.org/keys?action=AttachFile&do=view&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-{{ ansible_distribution_version }}"
  register: rpmfusiongpgkeys

- name: import rpmfusion repo GPG keys for Fedora
  rpm_key:
    state: present
    key: "{{ item }}"
  with_items:
    - "{{ rpmfusiongpgkeys.dest }}"
  when: ansible_distribution == 'Fedora'

- name: install rpmfusion repo using dnf for Fedora
  dnf:
    name: ['https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm', 'https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm']
    state: present
    enablerepo: True
    update_cache: True
  when: ansible_distribution == 'Fedora'

- name: download rpmfusion repo GPG keys for RedHat
  get_url:
    url: "{{ item }}"
    dest: "/tmp/"
    force: true
    owner: root
    group: root
    mode: 0644
  with_items:
    - "https://rpmfusion.org/keys?action=AttachFile&do=view&target=RPM-GPG-KEY-rpmfusion-free-el-{{ ansible_distribution_major_version|int }}"
    - "https://rpmfusion.org/keys?action=AttachFile&do=view&target=RPM-GPG-KEY-rpmfusion-nonfree-el-{{ ansible_distribution_major_version|int }}"
  register: rpmfusiongpgkeys

- name: import rpmfusion repo GPG keys for RedHat
  rpm_key:
    state: present
    key: "{{ item }}"
  with_items:
    - "{{ rpmfusiongpgkeys.dest }}"
  when: (ansible_distribution == 'RedHat') or (ansible_distribution == 'CentOS')

- name: install rpmfusion repo using dnf for RedHat
  dnf:
    name: ['https://download1.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_distribution_major_version|int }}.noarch.rpm','https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_distribution_major_version|int }}.noarch.rpm']
    state: present
    enablerepo: True
    update_cache: True
  when: (ansible_distribution == 'RedHat') or (ansible_distribution == 'CentOS')
