---
- name: import rpmfusion repo GPG keys for Fedora
  rpm_key:
    state: present
    key: "{{ item }}"
  with_items:
    - "7BDA98EF593050A34B1697ABA0EE9D83100BCD92"
    - "FE5A9393CB6E271B5A90CC1B0D9A76996DC1BE18"
  when: ansible_distribution == 'Fedora'

- name: install rpmfusion repo using dnf for Fedora
  dnf:
    name: ['https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm', 'https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm']
    state: present
    enablerepo: True
    update_cache: True
  when: ansible_distribution == 'Fedora'

- name: import rpmfusion repo GPG keys for RedHat
  rpm_key:
    state: present
    key: "{{ item }}"
  with_items:
    - "837935CD19E123AA7F8A8E69979F0C69158B3811"
    - "CF9FD59F61D6612146CDAC8E14B6792DBDDA8475"
  when: (ansible_distribution == 'RedHat') or (ansible_distribution == 'CentOS')

- name: install rpmfusion repo using dnf for RedHat
  dnf:
    name: ['https://download1.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_distribution_major_version|int }}.noarch.rpm','https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_distribution_major_version|int }}.noarch.rpm']
    state: present
    enablerepo: True
    update_cache: True
  when: (ansible_distribution == 'RedHat') or (ansible_distribution == 'CentOS')
