---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"
      skip: True
  when: (wireguard_package_name is not defined)

- name: install wireguard package
  package:
    name: "{{ wireguard_package_name }}"
    state: latest

- name: create wireguard config directory
  file:
    path: /etc/wireguard
    state: directory
    owner: root
    mode: 0700
