---
name: debug
'on':
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: 'ansible'

jobs:

  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'ansible'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible pyopenssl ndg-httpsclient pyasn1

      - name: Set up James user
        run: sudo useradd -m -c "james" james -s /bin/bash

      - name: Use more reliable Ubuntu apt mirror
        run: |
          sudo sed -i 's|http://azure.archive.ubuntu.com|https://ubuntu.osuosl.org|g' /etc/apt/sources.list && \
          sudo apt-get update

      - name: Run tests.
        run: ansible-playbook -vvv -i tests/inventory playbooks/simplenote-only.yml
        env:
          ANSIBLE_ROLES_PATH: '/home/runner/work/ansible/ansible/ansible/roles'
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          ANSIBLE_HOST_KEY_CHECKING: false
