---
- name: install latest versions of Samba daemon
  package:
    name: samba
    state: latest

- name: install latest versions of disk wiping and filesystem recovery tools
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - nwipe
    - testdisk
    - smartmontools

- name: install latest version of clamscan anti-virus tools
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - clamav
    - clamav-daemon
    - clamav-freshclam
    - clamdscan

- name: lay out copy-from-time-machine script to /usr/local/bin
  copy:
    src: copy-from-time-machine
    dest: /usr/local/bin/copy-from-time-machine
    owner: root
    group: root
    mode: 0744
