---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}-{{ ansible_distribution_major_version | int }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"
      skip: true
  when: (clamav_daemon_package_name is not defined) or (clamav_freshclam_package_name is not defined) or (gvfs_backend_package_name is not defined)

- name: install latest versions of Samba daemon
  package:
    name: samba
    state: latest

- name: install latest version of common clamscan anti-virus tools
  package:
    name:
      - clamav
      - "{{ clamav_daemon_package_name }}"
      - "{{ clamav_freshclam_package_name }}"
    state: latest

- name: install latest version of clamdscan on Debian-based systems
  package:
    name: clamdscan
    state: latest
  when: ansible_os_family == 'Debian'

- name: lay out copy-from-time-machine script to /usr/local/bin
  copy:
    src: copy-from-time-machine
    dest: /usr/local/bin/copy-from-time-machine
    owner: root
    group: root
    mode: 0744

- name: install latest versions of misc tools
  package:
    name:
      - rsync
      - inotify-tools
      - "{{ gvfs_backend_package_name }}"
    state: latest

# equivalent to sysctl -n -w fs.inotify.max_user_watches=16384
- name: "increase inotify max_user_watches limit"
  sysctl:
    name: fs.inotify.max_user_watches
    value: 16384
    sysctl_set: true
    state: present
    reload: true

# equivalent to sysctl -n -w fs.inotify.max_user_instances=512
- name: "increase inotify max_user_instances limit"
  sysctl:
    name: fs.inotify.max_user_instances
    value: 512
    sysctl_set: true
    state: present
    reload: true
