---
- name: install latest versions of Samba daemon
  package:
    name: samba
    state: latest

- name: install latest versions of disk wiping and filesystem recovery tools
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - nwipe
    - testdisk
    - smartmontools

- name: install latest version of clamscan anti-virus tools
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - clamav
    - clamav-daemon
    - clamav-freshclam
    - clamdscan
