---
- name: Install latest version of Terraform using APT
  include_tasks: setup-apt.yml
  when: ansible_pkg_mgr == 'apt'

- name: Install latest version of Terraform using DNF
  include_tasks: setup-dnf.yml
  when: ansible_pkg_mgr == 'dnf'

- name: Setup Terraform Local Environment
  include_tasks: setup-environment.yml
