---
- name: "apt | ensure Hashicorp Apt signing key present"
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: "apt | ensure Hashicorp repo present"
  copy:
    content:  "deb [arch=amd64] https://apt.releases.hashicorp.com focal main"
    dest: "/etc/apt/sources.list.d/hashicorp.list"
  register: hashicorp_repo

- name: "apt | update cache"
  apt:
    update_cache: true
  when: hashicorp_repo.changed

- name: "apt | ensure Terraform latest"
  apt:
    name: terraform
    state: latest
