---
- name: "apt | ensure Hashicorp Apt signing key present"
  shell: wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor > /etc/apt/keyrings/hashicorp.gpg

- name: "apt | ensure Hashicorp repo present"
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/hashicorp.gpg] https://apt.releases.hashicorp.com jammy main"
    state: present
    update_cache: true

- name: "apt | ensure Terraform latest"
  package:
    name: terraform
    state: latest
