---
- name: include RedHat ansible_distribution_release for RHEL
  include_vars: "../vars/RedHat.yml"
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- name: include Fedora ansible_distribution_release for fedora
  include_vars: "../vars/Fedora.yml"
  when: ansible_distribution == 'Fedora'

- name: Add Hashicorp repo
  yum_repository:
    name: hashicorp
    description: "Hashicorp Stable repository"
    baseurl: "https://rpm.releases.hashicorp.com/{{ ansible_distribution }}/{{ ansible_distribution_major_version }}/x86_64/stable"
    gpgkey: https://rpm.releases.hashicorp.com/gpg
    gpgcheck: true
    enabled: true

- name: "dnf | ensure Terraform present"
  dnf:
    name: terraform
    state: latest
