---
- name: Create qemu group if doesn't already exist
  group:
    name: qemu
    state: present

- name: Create qemu user if doesn't already exist
  user:
    name: qemu
    system: true
    groups: qemu,kvm

- name: Add your user to libvirt and qemu groups
  user:
    name: james
    groups: libvirt,qemu
    append: true

- name: create base VM directory
  file:
    path: "/VMs/"
    state: directory
    recurse: true
    owner: qemu
    group: qemu
    mode: 0775

- name: create ssh directory
  file:
    path: "/VMs/.ssh/"
    state: directory
    recurse: true
    owner: qemu
    group: qemu
    mode: 0700
